### ISSUE TITLE
mm2: autostretch stretches the histogram but not the image

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#101]
Using the demo configuration, snap an image.  Check Autostretch (if it was not checked).  Change the exposure time.  Note that the histogram "display line" behaves correctly, but the image does not (i.e. it gets brighter when increasing exposure, and gets darker when decreasing exposure).

**Comment by ChrisWeisiger** [comment]
Thanks for the report. This is now fixed. This may also be related to the other autostretch bug you reported.
