### ISSUE TITLE
Clarify policy on when summary metadata of datastore can be set

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#1016]
- Docs say can only be set once (good!)
- We probably need to also enforce only setting it before adding images
  - Except for rewritable datastores, of course
  - Does this restriction work, though?
  - See also `Pipeline.insertSummaryMetadata()` Javadoc

**Comment by nicost** [comment]
Note this is related to parts #1017 since most Storage methods rely on the summary metadata to "know" which axes they contain (or eventually will contain), so addressing remaining issues with Axes in DataProviders (and Datastores) need to know whether and how they can rely on SummaryMetadata.

**Comment by marktsuchida** [comment]
@nicost I though that made sense, but now I'm confused: what exactly do you mean by remaining issues with axes?

**Comment by marktsuchida** [comment]
(See #1210 regarding the "remaining issues with Axes".)
