### ISSUE TITLE
mm2: Closing confirmation to close all windows should cancel

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#108]
Using the "close" button, I'm prompted whether I want to close all opened window. If I close the dialog window using the close box, all windows are closed while I would expect it to act as hitting "cancel" and leaving all windows opened.

**Comment by ChrisWeisiger** [comment]
This is now fixed; the next nightly build (dated 20151124) of the beta will include the fix. Thanks for the report!
