### ISSUE TITLE
Linux build doesn't work as expected

### ISSUE THREAD

**Issue by tomhanak** [micro-manager/micro-manager#1130]
My recent contribution to MMCore ended up with additional set of commits fixing build on Mac (thanks Nico).
It built well on Windows and Linux (Ubuntu 18.04) with default configuration.

To avoid that situation in future I tried to restrict GCC to older C++ version by running `configure` like this:
```
./configure --enable-imagej-plugin=/usr/local/ImageJ CXXFLAGS="-std=c++03"
```
Unfortunately, the build then failed with a few unusual errors like missing headers although the code obviously includes them.

To make the story short, the root cause here seems to be the code uses e.g. `#ifdef linux` to wrap Linux-related code. The `linux` macro is obsolete and not POSIX compliant ([source](https://sourceforge.net/p/predef/wiki/OperatingSystems/), search 'Linux kernel' section).

To fix it the `__linux__` macro should be used instead. Optionally, MM could define project-wide macros like `MM_OS_LINUX`.

The `linux` macro is used only in about 20 files and half of the occurrences can be simply removed because the ifdef block is empty.

The workaround for now is to manually add the `linux` define, e.g.:
```
./configure --enable-imagej-plugin=/usr/local/ImageJ CXXFLAGS="-std=c++03 -Dlinux"
```

**Comment by nicost** [comment]
All occurrences of "linux" in pre-processor macros have been replaced with "__linux__".  Let me know if the -std=c++03 flag now works without modifications.
