### ISSUE TITLE
mm2: Inspector Window Show Info not showing all open MM2 windows.

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#115]
Open a dataset (I used the Open Recent(RAM) menu entry).  The Inspector window show a line with the image path, and a dropdown menu with "TopMost Window" and another line with the image path.  Click Tools Icon > Duplicate This Window.  Inspector now show a line with a name ending in "b", but "b" does not appear in the drop-down menu.

**Comment by ChrisWeisiger** [comment]
This is now fixed. Thanks for the report!
