### ISSUE TITLE
HamamatsuHam device adapter is not included in nightly builds

### ISSUE THREAD

**Issue by thirstythurston** [micro-manager/micro-manager#1155]
Hello,

I was trying to install micromanager on a Ti2 microscope with a Hamamatsu C14440-UP20 (I think) and I couldn't find the HamamatsuHam device adapter in the list. The DLL was also missing from the micromanager program folder. After some digging around because I love this software and have it installed on like 5 or 6 computers (you guys are great I can't pay you but every paper I get published references micromanager)  Oh wait the problem.  After digging around I found that both MM-gama2.0-20200212 and the MM1.4 from the same build had the Hamamatsu device adapter in the folder and it worked.  I also saw another issue in the python-micromanager repository saying Hamamatsu wasn't working.  This may be related?

Anyway take care

-Thurston

**Comment by nicost** [comment]
There were some issues due to updates to the code.  It should be present in tonight's build.  No need to re-open if that is not the case, I am working on the issue.  B.t.w., 20200212 is quite old, a build from a week ago should still include the adapter and be a lot more up to date.
