### ISSUE TITLE
mm2: File Open (RAM) blocks and does not give user feedback until the file loaded

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#120]
which is especially worry some with large files loading from a remote server (i.e. slow connection).  Loading a 2.6GB file takes about 30 seconds, and I do not get any feedback during that time.  Mouse clicks exert their effect after the file loaded (which can have bad consequences).

**Comment by ChrisWeisiger** [comment]
This is now fixed: users get a progress dialog to keep them updated. ProgressMonitor is a very handy class for this kind of thing.
