### ISSUE TITLE
Utilities DA Shutter does not offer "None" State

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/micro-manager#1256]
A digital State Device Shutter can be associated with a digital state device or not, by selecting the None option.

The analog equivalent - DA Shutter, does not offer a None option. That would be helpful to implement, particularly during troubleshooting.

**Comment by marktsuchida** [comment]
Agreed. A not-so-elegant workaround is to have a Demo DA device configured so that you can switch to it in lieu of "None".

**Comment by nicost** [comment]
Added (in mmCoreAndDevices repo).
