### ISSUE TITLE
Spinnaker Version 2.4.0 Leads to "AcquisitionStart" Parameter being not Writable in FLIR Cameras

### ISSUE THREAD

**Issue by JosephGreene** [micro-manager/micro-manager#1257]
Hi,

This is following up from this closed thread: https://github.com/micro-manager/micro-manager/issues/1060

In short, me and another micromanager user noticed that under Spinnaker 2.4.0, a parameter is disabled for my Blackfly S and his Oryx FLIR cameras. This inhibits the cameras from loading into Micromanager, even know they appear in the hardware configuration wizard. Fortunately, the other user indicates that switching to Spinnaker 2.3.0.77 [available in the FLIR Archive for Spinnaker] and selecting the VS2010 option does work for mm 2.0.0 gamma1 20210320. Just wanted to raise the issue with the new version!

Thank you!

**Comment by nicost** [comment]
Documentation has been updated to continue using Spinnaker 2.3.0.77.  Not sure what else could be done at this point (other than alerting FLIR to the problem).
