### ISSUE TITLE
how to debug  micro-manager with camera ?

### ISSUE THREAD

**Issue by lwxGitHub123** [micro-manager/micro-manager#1264]
hi,
      we want to debug  micro-manager   with  Raptor Photonics camera, we  could build  the C++ components,such as MMCoreJ and DemoCamera ,but we do not konw how to do next, could you give me an instructions  please ?

**Comment by marktsuchida** [comment]
If by "debug" you mean run with the Visual Studio debugger, then the best way is to build the `mmgr_dal_RaptorEPIX.dll` in Debug configuration, copy it to an existing Micro-Manager installation, start Micro-Manager by double-clicking, and then attach the debugger (https://docs.microsoft.com/en-us/visualstudio/debugger/attach-to-running-processes-with-the-visual-studio-debugger?view=vs-2019).

By the way, no big deal, but we encourage you to use https://forum.image.sc/ for support questions (please tag with 'micro-manager').

**Comment by lwxGitHub123** [comment]
got it; thank you very much !!!
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人: "micro-manager/micro-manager" ***@***.***&gt;;
 发送时间:&nbsp;2021年6月24日(星期四) 凌晨0:56
 ***@***.***&gt;;
 ***@***.******@***.***&gt;;
 主题:&nbsp;Re: [micro-manager/micro-manager] how to debug micro-manager with camera ? (#1264)

 

 

 
If by "debug" you mean run with the Visual Studio debugger, then the best way is to build the mmgr_dal_RaptorEPIX.dll in Debug configuration, copy it to an existing Micro-Manager installation, start Micro-Manager by double-clicking, and then attach the debugger (https://docs.microsoft.com/en-us/visualstudio/debugger/attach-to-running-processes-with-the-visual-studio-debugger?view=vs-2019).
 
By the way, no big deal, but we encourage you to use https://forum.image.sc/ for support questions (please tag with 'micro-manager').

**Comment by lwxGitHub123** [comment]
hi,
 &nbsp; I have post the questions in https://forum.image.sc/t/micro-manager-can-not-open-the-raptor-photonics-camera-and-build-rapp-failed/54391&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
 &nbsp; Thanks
 &nbsp; Liu
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人: "micro-manager/micro-manager" ***@***.***&gt;;
 发送时间:&nbsp;2021年6月24日(星期四) 凌晨0:56
 ***@***.***&gt;;
 ***@***.******@***.***&gt;;
 主题:&nbsp;Re: [micro-manager/micro-manager] how to debug micro-manager with camera ? (#1264)

 

 

 
If by "debug" you mean run with the Visual Studio debugger, then the best way is to build the mmgr_dal_RaptorEPIX.dll in Debug configuration, copy it to an existing Micro-Manager installation, start Micro-Manager by double-clicking, and then attach the debugger (https://docs.microsoft.com/en-us/visualstudio/debugger/attach-to-running-processes-with-the-visual-studio-debugger?view=vs-2019).
 
By the way, no big deal, but we encourage you to use https://forum.image.sc/ for support questions (please tag with 'micro-manager').
