### ISSUE TITLE
mm2: SetDisplaySettings API call throws null pointer exception

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#129]
Can be reproduced with the following script:
```
store = mm.data().createRAMDatastore();
display = mm.displays().createDisplay(store);
dsb = display.getDisplaySettings().copy();
display.setDisplaySettings(dsb.build());
```
And is caused by the use of the 'canvas_' variable in the SetDisplaySettings function without checking for null.  The variable is only set when an image is actually displayed.  However, as a script writer, it is quite logical to want to set the display settings before displaying images (and it becomes nasty to keep track of when one adds the first image to then set the display settings).

**Comment by ChrisWeisiger** [comment]
Yes, this should not be happening. Thanks for the report.

**Comment by ChrisWeisiger** [comment]
This should now be fixed. Thanks for the report!
