### ISSUE TITLE
MM2: Channel slider is inactive when in composite mode

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#130]
Which makes it impossible to review the per-image metadata.  It is weird that one has to change the display mode to a color or grayscale to review the per-image metadata.  Isn't it simpler to keep the slider the active?

**Comment by ChrisWeisiger** [comment]
Hm, hadn't thought of that side-effect. We wanted to make it clear that changing the channel when in composite view mode doesn't really "do anything", but forgot about the metadata panel. Thanks for the report.

**Comment by ChrisWeisiger** [comment]
This should now be fixed. Thanks for the report!
