### ISSUE TITLE
ASI Gamepad XY Speed Control

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/micro-manager#1379]
This is more of a question than an issue.

@jondaniels or @nicost  do you know if there is a way that I can program the Left Shoulder button of the XBox One controller to change the Multiplier property for XY movement of the Left Thumbstick such that we can cycle through three different scan speeds - slow, medium, and fast, by pressing the shoulder button? Is there a Beanshell script that will allow me to do that? This will make the wireless controller even more useful. Thanks in advance!

**Comment by jondaniels** [comment]
You can assign a beanshell script to run on the press of the button, though the image at https://micro-manager.org/ASI_Gamepad_Plugin don't show the trigger button as an option (I'm not sure why that is).  

Within the beanshell script you can check and set property values.  So what you describe could be done with code structured as follows (and you can write/test your script in the script editor separately):

`String val = mmc.getProperty(propertyName);
if (val.equals(propertyVal1)) mmc.setProperty(propertyName, propertyVal2);
else if (val.equals(propertyVal2)) mmc.setProperty(propertyName, propertyVal3);
else if (val.equals(propertyVal3)) mmc.setProperty(propertyName, propertyVal1);`

I don't recall offhand whether `equals` works for strings but you get the idea.

**Comment by ieivanov** [comment]
Hi Jon! 

Yes, that's my idea as well. My problem is that the XY scan speed is controlled through the Multiplier of the VectorMoveX property of the stage. The Multiplier is a feature in the plugin and not a MM device property that I can set with mmc.setProperty. Do you know if I can access the Multiplier setting of the gamepad plugin in a Beanshell script? Or do you maybe see a different strategy of doing this?

**Comment by jondaniels** [comment]
Oh, yes I see the problem.  I can see a few ways forward:
- the plugin could have an API allowing a script to get/set the multiplier
- the plugin could have hard-coded button behavior
- a new property could be added to the device adapter so scaling could be done with mmc.setProperty

I don't have time to work on this right now, but if you do then I'm guessing Nico would merge a PR.  The first solution seems the best in the long term (maybe there are other plugin aspects helpful to script?) and the last one is the quick and dirty solution that doesn't involve touching the plugin code and the one I would feel most comfortable tackling at a later time.

Adding my colleague @bls337 who may have ideas.

**Comment by ieivanov** [comment]
Thanks Jon, and sorry for the late reply. I'm more of a hacker than a developer when it comes to Java programming, so I'd appreciate any help from you or your team that I can get.

**Comment by bls337** [comment]
I just submitted a pull request that adds an API to the Gamepad plugin. Once it's merged you can use a Beanshell script to get and set the multiplier for entries in the "Axis Assignment Table". You need to open the plugin so that the API has access to the table. GamepadAPI.Axis is an enum that corresponds to the axis names in the table. Here's an example Beanshell script:

```
import com.asiimaging.asi_gamepad.GamepadAPI;

GamepadAPI.setAxisMultiplier(GamepadAPI.Axis.LEFT_THUMBSTICK_X, 3.0);
print("Multiplier: " + GamepadAPI.getAxisMultiplier(GamepadAPI.Axis.LEFT_THUMBSTICK_X));
```

This is for Micro-Manager 2.0, so if you need this feature in MM 1.4 please let me know.

**Comment by marktsuchida** [comment]
Ref: #1383.

**Comment by ieivanov** [comment]
Thank you! I'll test it in the next couple of days and I'll let you know if I run into any problems. I'll close this issue for now.

**Comment by ieivanov** [comment]
@bls337 I have a problem running the example script you provided on MM nightly build 02_03_2022, I get an error saying 

```
Line 3: evaluation error : Sourced file: inline evaluation of: ``import com.asiimaging.asi_gamepad.GamepadAPI;  GamepadAPI.setAxisMultiplier(Game . . . '' : Class or variable not found: GamepadAPI.Axis.LEFT_THUMBSTICK_X
```

The plugin is open and the controller is connected and responds to joystick commands. However, it seems like I'm running into a problem with the new API. Could you please help with this?

**Comment by marktsuchida** [comment]
This could be due to #916. (Sorry, it didn't occur to me when merging #1383.)

**Comment by marktsuchida** [comment]
@bls337 The official way for now is to have separate "library" and "plugin" Jars (see the `libraries/` directory in the source tree). The library Jars are placed on the classpath, just like any external dependency listed in `buildscripts/ivy.xml`, so can be accessed from plugins and BeanShell scripts. This is done, for example, by the Projector plugin, which has an API.

The catch is that libraries cannot access plugin classes either, so the bulk of the code would need to move to the library (depending on how well logic code is separated from GUI code). The plugin would then contain the GUI code and plugin class, and call classes in the library.

**Comment by bls337** [comment]
@marktsuchida What will be the standard practice in the future? Will the separation between libraries and plugins still exist?

**Comment by ieivanov** [comment]
Hi @bls337, your suggestion to place the Gamepad.jar file in the `C:\Program Files\Micro-Manager-2.0\plugins\Micro-Manager` directory allowed me to change the multiplier from a command through the Micro-manager scripting panel, but not when I save same script as a beanshell file and link it to one of the buttons of the XBox controller. Is this another caveat of the different environments?

**Comment by ieivanov** [comment]
Never mind, I got it to work. I had forgotten to specify "Ren_Beanshell_script" under Action, even though I had provided the script path. 

Thanks for your help @bls337. Moving the jar file is a good enough fix for me, I'll let the two of you decide on the long-term solution. You're welcome to close this ticket for now.

**Comment by bls337** [comment]
Awesome, I'm glad it's working for you. I think the long term solution is to keep things as is and wait until the plugin system is updated, then you will be able access the API through Beanshell without moving the file.
