### ISSUE TITLE
mm.live().getDisplay().setFullScreen(true) does not work

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#1416]
I believe that is because the course code in DisplayController.java has the following line of code:

   @Override
   public void setFullScreen(boolean enable) {
      throw new UnsupportedOperationException();
   }

I am not quite sure why this function is in the API but not implemented. The actual code setting fullscreen mode is in org.micromanager.display.internal.displayWindow.DisplayUIController:setFullScreenMode(boolean fullScreen).

**Comment by marktsuchida** [comment]
I think most likely it got forgotten (probably by me, when I rewrote large parts of the display code).

Alternatively, it is possible that it was not felt safe to directly expose `DisplayUIController.setFullScreenMode()` without additional checks -- maybe there are conditions under which it is not safe to call it. In a very quick test on Windows, I find that if I start an MDA (with long-ish exposure time) and switch to full screen before the first image arrives, there is a glitch in which the non-full-screen window appears on top of the full-screen window when the first image arrives.
