### ISSUE TITLE
Can't run MM on Mac OS 12

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/micro-manager#1510]
Using recent nightly builds and Mac OS 12.4, I'm unable to run Micro-Manager at all. I get the error: 

`Can't load library .... libMMCoreJ_wrap.jnilib`

I can't seem to figure out what causes this. I tried `chmod`ing the permissions on that file but no difference. It doesn't seem to show up in the Mac OS security settings where I can allow it to run like ImageJ.

Strangely, I can run it when I launch it via pycro-manager headless mode, or when I run MM from IntelliJ (after clicking through a series of "open anyway" dialogs for both libMMCoreJ_wrap.jnilib and the demo camera device adapter), which suggests to me that it is something about the imageJ launcher, rather than the file itself.

Overall, it is getting to be quite difficult to use MM on Mac because of this unidentified developer stuff and increasingly stringent security settings

**Comment by marktsuchida** [comment]
#1036. I think it works if you build everything from scratch. Need signed installer (#396) for GUI app to work smoothly.

**Comment by marktsuchida** [comment]
See #2001.
