### ISSUE TITLE
Ratio Imaging plugin

### ISSUE THREAD

**Issue by SaeedArshad194** [micro-manager/micro-manager#1515]
I am using two cameras to measure FRET, Nico said  the problem is that the plugin only lists the channels in the Channel group, and not the “composite” channel names you get with the MultiCamera plugin. Who can fix the bug?

**Comment by nicost** [comment]
Should work after merge of #1519.  Please test and provide feedback.  I believe this already is in the latest nightly build. Now waiting for someone wanting to do this with the SplitView plugin.

**Comment by nicost** [comment]
Closing due to lack of feedback.
