### ISSUE TITLE
Magellan plugin: Explore mode does not show images

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#1535]
Not sure how to reproduce this, but I very regularly encounter a situation where the Explore mode seems to take images, but does not display them in the viewer.  Encountering it right now, I see expected light flashes for each image, but nothing appears on the screen.  

Logs show: 
```
2022-10-24T14:27:44.076789 tid1500 [IFO,App] Thread 469 (NDViewer Acquisition closing thread) terminated with uncaught exception
2022-10-24T14:27:44.076789 tid1500 [IFO,App] java.lang.NullPointerException
2022-10-24T14:27:44.076789 tid1500 [IFO,App]   at org.micromanager.ndviewer.main.NDViewer$3.run(NDViewer.java:701)
2022-10-24T14:27:44.076789 tid1500 [IFO,App]   at java.lang.Thread.run(Thread.java:748)
```
which is repeated when closing the acquisition (now on another thread).  

Happy to help trouble shoot, but more logging output will make this easier.

**Comment by henrypinkard** [comment]
I think it might be a race condition when the viewer is trying to close the acquisition. Maybe this will fix it:

https://github.com/micro-manager/NDViewer/pull/15/files#diff-8abf35e6304fd676b653d220e9819dcbcf0feeb4e2b745c81a7fccc8c61d2a25

You can drop in NDViewer 0.5.4 jar from [here](https://s01.oss.sonatype.org/#nexus-search;quick~micro-manager)

But I don't think that explains why the images wouldn't show up so there could be something else going on here

**Comment by nicost** [comment]
In my development environment, using the demo camera, I also run into a problem.  In this case, the EDT logger produces the following output, with the EDT apparently stuck:

Thread 18 [AWT-EventQueue-0] RUNNABLE
                                    [       ]   at sun.java2d.pisces.Stroker.emitReverse(Stroker.java:423)
                                    [       ]   at sun.java2d.pisces.Stroker.finish(Stroker.java:446)
                                    [       ]   at sun.java2d.pisces.Stroker.moveTo(Stroker.java:356)
                                    [       ]   at sun.java2d.pisces.Dasher.goTo(Dasher.java:155)
                                    [       ]   at sun.java2d.pisces.Dasher.lineTo(Dasher.java:210)
                                    [       ]   at sun.java2d.pipe.RenderingEngine.feedConsumer(RenderingEngine.java:366)
                                    [       ]   at sun.java2d.pisces.PiscesRenderingEngine.pathTo(PiscesRenderingEngine.java:484)
                                    [       ]   at sun.java2d.pisces.PiscesRenderingEngine.strokeTo(PiscesRenderingEngine.java:363)
                                    [       ]   at sun.java2d.pisces.PiscesRenderingEngine.strokeTo(PiscesRenderingEngine.java:163)
                                    [       ]   at sun.java2d.pisces.PiscesRenderingEngine.getAATileGenerator(PiscesRenderingEngine.java:562)
                                    [       ]   at sun.java2d.pipe.AAShapePipe.renderPath(AAShapePipe.java:147)
                                    [       ]   at sun.java2d.pipe.AAShapePipe.draw(AAShapePipe.java:78)
                                    [       ]   at sun.java2d.pipe.PixelToParallelogramConverter.draw(PixelToParallelogramConverter.java:148)
                                    [       ]   at sun.java2d.SunGraphics2D.draw(SunGraphics2D.java:2497)
                                    [       ]   at org.micromanager.ndviewer.internal.gui.contrast.HistogramPanel.drawCursor(HistogramPanel.java:159)
                                    [       ]   at org.micromanager.ndviewer.internal.gui.contrast.HistogramPanel.paintComponent(HistogramPanel.java:715)
                                    [       ]   at javax.swing.JComponent.paint(JComponent.java:1056)
                                    [       ]   at org.micromanager.ndviewer.internal.gui.contrast.ChannelControlPanel$5.paint(ChannelControlPanel.java:277)
                                    [       ]   at javax.swing.JComponent.paintChildren(JComponent.java:889)
                                    [       ]   at javax.swing.JComponent.paint(JComponent.java:1065)
                                    [       ]   at javax.swing.JComponent.paintChildren(JComponent.java:889)
                                    [       ]   at javax.swing.JComponent.paint(JComponent.java:1065)
                                    [       ]   at javax.swing.JComponent.paintChildren(JComponent.java:889)
                                    [       ]   at javax.swing.JComponent.paint(JComponent.java:1065)
                                    [       ]   at javax.swing.JComponent.paintChildren(JComponent.java:889)
                                    [       ]   at javax.swing.JComponent.paint(JComponent.java:1065)
                                    [       ]   at javax.swing.JViewport.paint(JViewport.java:728)
                                    [       ]   at javax.swing.JComponent.paintChildren(JComponent.java:889)
                                    [       ]   at javax.swing.JComponent.paint(JComponent.java:1065)
                                    [       ]   at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
                                    [       ]   at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
                                    [       ]   at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
                                    [       ]   at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
                                    [       ]   at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
                                    [       ]   at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
                                    [       ]   at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
                                    [       ]   at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
                                    [       ]   at java.security.AccessController.doPrivileged(Native Method)
                                    [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
                                    [       ]   at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
                                    [       ]   at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
                                    [       ]   at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
                                    [       ]   at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
                                    [       ]   at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
                                    [       ]   at java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:311)
                                    [       ]   at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
                                    [       ]   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
                                    [       ]   at java.awt.EventQueue.access$500(EventQueue.java:97)
                                    [       ]   at java.awt.EventQueue$3.run(EventQueue.java:709)
                                    [       ]   at java.awt.EventQueue$3.run(EventQueue.java:703)
                                    [       ]   at java.security.AccessController.doPrivileged(Native Method)
                                    [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
                                    [       ]   at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
                                    [       ]   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
                                    [       ]   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
                                    [       ]   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
                                    [       ]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
                                    [       ]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
                                    [       ]   at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
                                    [       ] Thread 21 [DestroyJavaVM] RUNNABLE

I'll try to debug ndviewer, but I do have the feeling there are issues with AWT/Swing, etc..

**Comment by nicost** [comment]
This error can be avoided by using Java 1.8.0_152 (bundled with Micro-Manager), but pops up with Java 1.8.0_312.  I believe it signifies issues with the UI that may manifest themselves in other ways as well.  However, I do not understand the underlying issue (i.e. why is the EDT not proceeding?)

**Comment by henrypinkard** [comment]
Oh yeah, I think we've seen this before: https://github.com/micro-manager/NDViewer/issues/10

I also have no idea what the underlying issue is, and if I recall correctly it works differently with different JDK8 implementations. My environment is set up with Zulu 1.8.0_332 and that seems to work fine. I've also seen that it seems to always work with newer JDKs (specifically JDK11). 

Since it works with newer Java versions, and I have not the slightest idea what is causing it or how to fix it, my preference is to ignore the problem until it goes away in a future update :)

**Comment by nicost** [comment]
This may be related: https://github.com/adoptium/temurin-build/issues/716.  I was hoping this is related to the issue I am seeing on the actual microscope....

**Comment by henrypinkard** [comment]
Hmmm so maybe an update to JFreeChart or add that command line argument would fix it?

Unfortunately, I doubt this is the cause of the issue you were seeing, because there was no data being saved on your system, and the are entirely separate components (unless something super weird is happening with Java)

**Comment by nicost** [comment]
Discovered that the affected system was running a Micro-Manager version of a few months ago.  Updating to the latest fixed the problem.  Not quite sure what the underlying problem was, but happy things are working.

**Comment by henrypinkard** [comment]
Nice!
