### ISSUE TITLE
MultiPage Tiff storage goes balistic under certain conditions

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#1579]
Disocovered by Tanner Fadero.  Steps to reproduce (beware, this may fill up your harddrive!) with the democamera:
- Set the camera size to something big, for instance: 2500x2000 (i.e. ~10MB for each 16bit image)
- Run an MDA with multiple positions (for instance: 10), 2 channels, and 200 z positions.  Make sure that Options - Save XY position in ... is checked and that the acquisition order is Position, Channel, Slice, and that the data are saved as "Image Stack File"
- Discover that instead of one file per position, there are hundreds of files in the target location, each 3.9GB.  With a little luck your hard drive will be full with unusable data.

It seems this bug is triggered by the size of one position exceeding 3.9GB.

**Comment by marktsuchida** [comment]
This reminds me of the discussion we had in #1415. Could it be an edge case in the code that was changed in that PR, such that the fallback is not working?

A good way to test this, by the way, is to create a fixed-size disk image and save to it, so that your main drive doesn't fill up.

Cc: @dickinson-lab in case they have any insight.

**Comment by henrypinkard** [comment]
An easy test would be to run the same thing with NDtiff and see if you get the same behavior. If not, then it is something wrong with that splitting files logic mark points out, likely

**Comment by nicost** [comment]
Plot thickens a bit, this only happens with an image size of 2250 x 2550, i.e. 2500 x 2500 is OK.

**Comment by dickinson-lab** [comment]
Does it happen with bigger or smaller images too, or is it only that exact size that is problematic?

Best,
Dan

Sent from my phone - please excuse short responses and typos
________________________________

**Comment by nicost** [comment]
Don't exactly know where the boundaries are, 2500 x 2500 is OK, I have not extensively tested more sizes, now focussing on detangling the code:

```
      if (splitByFrame) {
         size = singleImageBytes * axis1ImagesLeft
               + singleImageBytes * axis1Size * axis2ImagesLeft
               + SPACE_FOR_COMMENTS + numChannels_ * DISPLAY_SETTINGS_BYTES_PER_CHANNEL
               + extraPadding + filePosition_;
         size += omeMDLength;
```
This calculation does not seem to be correct, but will need some time to make it (more) correct.

**Comment by dickinson-lab** [comment]
Thanks Nico! Glad it was a quick fix.

Best,
Dan

Sent from my phone - please excuse short responses and typos
________________________________
