### ISSUE TITLE
mm2: Autostretch broken for 8-bit images

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#162]
With the demo camera in 8-bit mode, StripeWidth=0.1, exposure = 100 ms, Autostretch and Auto once give incorrect ranges in the histogram view. Also not sure how the images are actually being scaled in this case.

**Comment by marktsuchida** [comment]
It might be that autostretch is working correctly but the intensity range is drawn incorrectly over the histogram.

**Comment by marktsuchida** [comment]
It might be that autostretch is working correctly but the intensity range is drawn incorrectly over the histogram.
Stretch the Inspector horizontally to see this symptom.

**Comment by ChrisWeisiger** [comment]
Display of 8-bit images seems to have problems in general. The contrast settings are correctly calculated, but the image is drawn as far too dim; effectively the display appears to be locked in a 16-bit display mode even if the data is 8-bit. Note that composite and RGB 8-bit images both work, at least in terms of producing a usable image; the histogram display is still wrong.

**Comment by ChrisWeisiger** [comment]
Both of these issues should now be fixed.
