### ISSUE TITLE
3-point z-plane focus device

### ISSUE THREAD

**Issue by fadero** [micro-manager/micro-manager#1639]
@nicost (I don't fully understand the problem, but I'll do my best to describe it here). When you use 3-point Z-plane focus correction in the HCS Site Generator, it uses the correct selected focus device (in my case, Z drive). However, when you try to visit a point, it uses the wrong focus device (the core focus device; in my case, the piezo) to correct for any z-offset from the plate being tilted. 

To hack this, I have to manually change the core focus device to the Z drive while I am moving around my plate, then remember to change the core focus device back to piezo for my multi-dimensional acquisition.

**Comment by nicost** [comment]
Should be fixed in PR #1641.  If not, please re-open.  Thanks for reporting!
