### ISSUE TITLE
API's autostretch() method

### ISSUE THREAD

**Issue by chipuff** [micro-manager/micro-manager#1652]
Hi,
According to the MM 2.0 documentation, there is a method on the DisplayWindow interface called autostretch() that programmatically does the equivalent of clicking the 'Autostretch Once' button in the Inspect window when Live mode is activated –
 
https://valelab4.ucsf.edu/~MM/doc-2.0.0-beta/mmstudio/org/micromanager/display/DisplayWindow.html#autostretch()

When trying to use this function (via pycro-manager), however, it resulted in an UnsupportedOperationException error. 

The documentation states that the DisplayWindow interface is implemented by DefaultDisplayWindow, so I had a look in the recent source code, and although I couldn’t find that, I did find a class called DisplayController that implements that interface, however, the function reads as this: -

   @Override
   public void autostretch() {
      throw new UnsupportedOperationException();
   }

which seems to explain the error message :)

Is this a case that the documentation being aspirational and ahead of the code base, or was this function temporarily and permanently deprecated for some reason? 
Is there perhaps a reason why implementing this functionally might be tricky / have unexpected traps? The code to do that functionality must exist, and clicking the 'Autostretch Once' button in the UI works great.

Otherwise, perhaps there is there simply another approach to achieve the same effect, such as a way to programmatically check, then uncheck the Autostrech check box?

Any opinions or advice would be very welcome.

Thanks.

**Comment by nicost** [comment]
Oversight.  I made an implementation in PR #1653.  We should probably check for other API methods that are not implemented.
