### ISSUE TITLE
HCS Site Generator should support typewriter vs snake selection

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#166]
See: http://micro-manager.3463995.n2.nabble.com/Questions-on-Hamamatsu-Flash4-tp7586424p7586618.html

The GUI on the right-hand side is getting a little complicated. Perhaps it warrants some grouping.

**Comment by ChrisWeisiger** [comment]
See also commit 15939 by Nico in the 1.4 SVN: https://valelab.ucsf.edu/trac/micromanager/changeset/15939

**Comment by ChrisWeisiger** [comment]
This is now done.
