### ISSUE TITLE
mm2: add ability to transparently wrap portion of profile

### ISSUE THREAD

**Issue by ChrisWeisiger** [micro-manager/micro-manager#167]
The desired behavior is to say "give me a PropertyMap that contains/provides access to all profile keys" so that users can interact with the PropertyMap without having to specify the class, and when they modify the PropertyMap it transparently updates the profile.

Of course, this requires a writable variant of the PropertyMap, too.

**Comment by marktsuchida** [comment]
See `MutablePropertyMapView`.
