### ISSUE TITLE
Make it easy to do time-lapses with different channel settings at different locations

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#1685]
Example: have a multi-well plate with cells expressing different construct.  To run a time lapse in all wells simultaneously, we need a mechanism to specify MDA settings at each site, and then execute them all in the same acquisition engine loop.  This may be possible in AcqEngineJ (@henrypinkard  is that true?). Next challenge is then to design an easy, elegant UI that lets user specify different settings at different sites.

**Comment by henrypinkard** [comment]
Yep, should be possible. The UI is the challenge

**Comment by nicost** [comment]
Addressed in #1737
