### ISSUE TITLE
ImageProcessing.jar missing on MacOS/linux builds

### ISSUE THREAD

**Issue by ilyasdc** [micro-manager/micro-manager#1691]
Tested on MacOS with MM build 20230426 (from the website)

```bash
ls /Applications/Micro-Manager-2.0.1-20230426/plugins/ImageProcessing.jar
ls: /Applications/Micro-Manager-2.0.1-20230426/plugins/ImageProcessing.jar: No such file or directory
```
I also built MM on linux, in the build directory, the .jar file is present. **the fix is just to copy the missing file to the plugins/Micro-manager/**

**As a consequence it seems that the oughtafocus isn't loaded.**

NB: On windows all is fine.

**Comment by marktsuchida** [comment]
Thank you for catching this!
