### ISSUE TITLE
Beanshell running old versions of functions

### ISSUE THREAD

**Issue by ChrisWeisiger** [micro-manager/micro-manager#170]
Repro case: 

```
void printme(int i) {
    print("I is " + i);
}
for (int i = 0; i < 10; ++i) {
   printme(i);
}
```

Run this, then modify printme to change the print statement, and run it again; note the output still references the old function. Tested in 2.0, 1.4.22, and 1.4.13 and it all reproduces.

**Comment by ChrisWeisiger** [comment]
Alternate repro doable without the scripting panel (i.e. just with the REPL):

`void run(i) {print("Hello, " + i);}`
`void run(i) {print("Goobye, " + i);}`
`run(0)`

will print `Hello, 0`.

This also reproduces in Fiji's Beanshell scripting system, so it is probably a bug in Beanshell itself.

**Comment by ChrisWeisiger** [comment]
Per http://forum.imagej.net/t/alternative-to-beanshell/805 Curtis recommends we investigate the possibility of using Groovy instead.

**Comment by ChrisWeisiger** [comment]
Upgrading to Beanshell 2.0b6 fixes the first repro case, but not the second one.

**Comment by marktsuchida** [comment]
In my hands BeanShell 2.0b6 fixes neither repro case.

Added `mm.scripter().resetInterpreter();`, which can be used to clear the interpreter namespace. This can be used to work around the first repro case. It can be called at the beginning of a script during debugging to ensure method definitions are not stale.

Fixing the second repro case would of course require fixing BeanShell itself.

**Comment by nicost** [comment]
@marktsuchida  OK to close?

**Comment by marktsuchida** [comment]
Yeah, the only fix would be to move away from a buggy and unmaintained language.
