### ISSUE TITLE
mm2: Script Panel console hard to read in "Night" color scheme

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#171]
Technical issues make it hard to adjust text color. Perhaps the console should be bright-background even when in Night mode, matching the upper script editor area.

**Comment by nicost** [comment]
Not sure whether the console is the top right or bottom right panel. Currently, bottom right has dark background with white fonts and top right has light background with colored fonts (in night mode).  Don't see obvious improvement possibilities (possible make the top right background dark as well).
