### ISSUE TITLE
Installation error PVCam

### ISSUE THREAD

**Issue by kmpape** [micro-manager/micro-manager#1713]
Hi,

I am trying to rebuild MM. Following your guide, it throws an error when calling make:

`Making all in PVCAM`
`In file included from AcqConfig.cpp:1:
AcqConfig.h:252:33: error: ‘PL_FRAME_SUMMING_FORMAT_16_BIT’ was not declared in this scope
  252 |     int HostFrameSummingFormat{ PL_FRAME_SUMMING_FORMAT_16_BIT };
`

Does someone have an idea why? Last time we built MM it was with a commit from Nov 22. I just pulled the newest commit. The variable PVCAM_SDK_PATH is set, and PVCAM_VERSION gives 3.9.11.2.

Any help is greatly appreciated. Thank you very much.

**Comment by marktsuchida** [comment]
I believe you need PVCAM 3.10.0.0 for the latest code (since late Jan 2023).
