### ISSUE TITLE
OughtaFocus plugin is missing from 2.0

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#172]
OughtaFocus ended up being one of the most useful autofocus plugins.  The ASIdiSPIM plugin relies on it being present.  Was it never ported or was there another reason not to include it in the current 2.0 distribution?

**Comment by marktsuchida** [comment]
@ChrisWeisiger was fixing this issue right around when it was filed :)

**Comment by marktsuchida** [comment]
Whoops, looks like it wasn't pushed yet.

**Comment by ChrisWeisiger** [comment]
This is now fixed. Apologies for the inconvenience.
