### ISSUE TITLE
Reloading HW config buggy when config group of same name exists

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#173]
E.g. Load the demo config, then load a real config containing 'Channel' group. The contents of the Channel group are wrong.

**Comment by ChrisWeisiger** [comment]
Whatever's going wrong here isn't specifically to do with config group names. If I create a config file with a "Channel" config group but nothing else, then switch in the demo config file, then the first config group (which happens to be "Camera") will have the old config file's Channel group options. Once I try to interact with any of the config groups, I'll get an error complaining that I tried to set the Camera group to an invalid value, after which the UI will start behaving itself properly.

**Comment by marktsuchida** [comment]
@zhangxiaosa and I cannot reproduce this with current versions.
