### ISSUE TITLE
Micro-Magellan: Zooming out before snapping an image hangs the UI

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#1730]
Reproduced with Demo configuration.  Start an Explore acquisition, then press the minus button.  UI hangs with this Stacktrace:

2023-06-29T10:10:27.063235 tid9384 [IFO,App] EDTHangLogger: Missed heartbeat; waiting to see if we are stuck on a single event
2023-06-29T10:10:28.069208 tid9384 [IFO,App] EDTHangLogger: Event handling has exceeded at least 1004 ms (currently 5514 ms since heartbeat timebase)
                                   [       ] Stack traces follow (note: thread states queried later than stack traces)
                                   [       ] Thread 2 [Reference Handler] WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at java.lang.Object.wait(Object.java:502)
                                   [       ]   at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
                                   [       ]   at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
                                   [       ] Thread 3 [Finalizer] WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
                                   [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
                                   [       ]   at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)
                                   [       ] Thread 5 [Signal Dispatcher] RUNNABLE
                                   [       ] Thread 6 [Attach Listener] RUNNABLE
                                   [       ] Thread 13 [RMI TCP Accept-0] RUNNABLE
                                   [       ]   at java.net.DualStackPlainSocketImpl.accept0(Native Method)
                                   [       ]   at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:131)
                                   [       ]   at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
                                   [       ]   at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
                                   [       ]   at java.net.ServerSocket.implAccept(ServerSocket.java:545)
                                   [       ]   at java.net.ServerSocket.accept(ServerSocket.java:513)
                                   [       ]   at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:400)
                                   [       ]   at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:372)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 14 [RMI Reaper] WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
                                   [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
                                   [       ]   at sun.rmi.transport.ObjectTable$Reaper.run(ObjectTable.java:351)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 15 [GC Daemon] TIMED_WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at sun.misc.GC$Daemon.run(GC.java:117)
                                   [       ] Thread 16 [Java2D Disposer] WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
                                   [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
                                   [       ]   at sun.java2d.Disposer.run(Disposer.java:148)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 17 [AWT-Shutdown] WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at java.lang.Object.wait(Object.java:502)
                                   [       ]   at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:295)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 18 [AWT-Windows] RUNNABLE
                                   [       ]   at sun.awt.windows.WToolkit.eventLoop(Native Method)
                                   [       ]   at sun.awt.windows.WToolkit.run(WToolkit.java:306)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 20 [AWT-EventQueue-0] BLOCKED
                                   [       ]   at org.micromanager.ndviewer.internal.gui.ImageMaker.removeImageProcessor(ImageMaker.java:90)
                                   [       ]   at org.micromanager.ndviewer.main.NDViewer$1.run(NDViewer.java:370)
                                   [       ]   at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
                                   [       ]   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
                                   [       ]   at java.awt.EventQueue.access$500(EventQueue.java:97)
                                   [       ]   at java.awt.EventQueue$3.run(EventQueue.java:709)
                                   [       ]   at java.awt.EventQueue$3.run(EventQueue.java:703)
                                   [       ]   at java.security.AccessController.doPrivileged(Native Method)
                                   [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
                                   [       ]   at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
                                   [       ]   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
                                   [       ]   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
                                   [       ]   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
                                   [       ]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
                                   [       ]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
                                   [       ]   at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
                                   [       ] Thread 23 [DestroyJavaVM] RUNNABLE
                                   [       ] Thread 27 [TimerQueue] WAITING
                                   [       ]   at sun.misc.Unsafe.park(Native Method)
                                   [       ]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
                                   [       ]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
                                   [       ]   at java.util.concurrent.DelayQueue.take(DelayQueue.java:211)
                                   [       ]   at javax.swing.TimerQueue.run(TimerQueue.java:174)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 28 [User Profile Saver Pool Thread 0] TIMED_WAITING
                                   [       ]   at sun.misc.Unsafe.park(Native Method)
                                   [       ]   at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
                                   [       ]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
                                   [       ]   at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
                                   [       ]   at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 30 [EDTHangLogger timer] RUNNABLE
                                   [       ]   at java.lang.Thread.dumpThreads(Native Method)
                                   [       ]   at java.lang.Thread.getAllStackTraces(Thread.java:1610)
                                   [       ]   at org.micromanager.internal.diagnostics.EDTHangLogger.checkForHang(EDTHangLogger.java:226)
                                   [       ]   at org.micromanager.internal.diagnostics.EDTHangLogger.access$100(EDTHangLogger.java:33)
                                   [       ]   at org.micromanager.internal.diagnostics.EDTHangLogger$2.run(EDTHangLogger.java:213)
                                   [       ]   at java.util.TimerThread.mainLoop(Timer.java:555)
                                   [       ]   at java.util.TimerThread.run(Timer.java:505)
                                   [       ] Thread 31 [Thread-4] TIMED_WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at bsh.util.JConsole$BlockingPipedInputStream.read(JConsole.java:771)
                                   [       ]   at java.io.PipedInputStream.read(PipedInputStream.java:377)
                                   [       ]   at java.io.InputStream.read(InputStream.java:101)
                                   [       ]   at bsh.util.JConsole.inPipeWatcher(JConsole.java:667)
                                   [       ]   at bsh.util.JConsole.run(JConsole.java:677)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 32 [BeanShell interpreter] TIMED_WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at java.io.PipedInputStream.read(PipedInputStream.java:326)
                                   [       ]   at java.io.PipedInputStream.read(PipedInputStream.java:377)
                                   [       ]   at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
                                   [       ]   at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
                                   [       ]   at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
                                   [       ]   at java.io.InputStreamReader.read(InputStreamReader.java:184)
                                   [       ]   at bsh.JavaCharStream.FillBuff(JavaCharStream.java:160)
                                   [       ]   at bsh.JavaCharStream.ReadByte(JavaCharStream.java:188)
                                   [       ]   at bsh.JavaCharStream.readChar(JavaCharStream.java:289)
                                   [       ]   at bsh.JavaCharStream.BeginToken(JavaCharStream.java:209)
                                   [       ]   at bsh.ParserTokenManager.getNextToken(ParserTokenManager.java:2072)
                                   [       ]   at bsh.Parser.jj_ntk(Parser.java:6022)
                                   [       ]   at bsh.Parser.Line(Parser.java:163)
                                   [       ]   at bsh.Interpreter.Line(Interpreter.java:1011)
                                   [       ]   at bsh.Interpreter.run(Interpreter.java:462)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 35 [ZMQ Server ] RUNNABLE
                                   [       ]   at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
                                   [       ]   at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
                                   [       ]   at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
                                   [       ]   at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
                                   [       ]   at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
                                   [       ]   at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
                                   [       ]   at zmq.Signaler.waitEvent(Signaler.java:129)
                                   [       ]   at zmq.Mailbox.recv(Mailbox.java:90)
                                   [       ]   at zmq.SocketBase.processCommands(SocketBase.java:911)
                                   [       ]   at zmq.SocketBase.recv(SocketBase.java:834)
                                   [       ]   at org.zeromq.ZMQ$Socket.recv(ZMQ.java:3358)
                                   [       ]   at org.zeromq.ZMQ$Socket.recv(ZMQ.java:3339)
                                   [       ]   at org.micromanager.internal.zmq.ZMQSocketWrapper.receiveMessage(ZMQSocketWrapper.java:188)
                                   [       ]   at org.micromanager.internal.zmq.ZMQServer.lambda$initialize$2(ZMQServer.java:109)
                                   [       ]   at org.micromanager.internal.zmq.ZMQServer$$Lambda$159/275035091.call(Unknown Source)
                                   [       ]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 36 [reaper-1] RUNNABLE
                                   [       ]   at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
                                   [       ]   at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
                                   [       ]   at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
                                   [       ]   at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
                                   [       ]   at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
                                   [       ]   at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
                                   [       ]   at zmq.poll.Poller.run(Poller.java:234)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 37 [iothread-2] RUNNABLE
                                   [       ]   at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
                                   [       ]   at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
                                   [       ]   at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
                                   [       ]   at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
                                   [       ]   at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
                                   [       ]   at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
                                   [       ]   at zmq.poll.Poller.run(Poller.java:234)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 40 [Swing-Shell] WAITING
                                   [       ]   at sun.misc.Unsafe.park(Native Method)
                                   [       ]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
                                   [       ]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
                                   [       ]   at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                   [       ]   at sun.awt.shell.Win32ShellFolderManager2$ComInvoker$3.run(Win32ShellFolderManager2.java:547)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 41 [Multipage Tiff data writing executor] WAITING
                                   [       ]   at sun.misc.Unsafe.park(Native Method)
                                   [       ]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
                                   [       ]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
                                   [       ]   at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 42 [Display calculation executor] RUNNABLE
                                   [       ]   at org.micromanager.ndtiffstorage.NDTiffStorage.getDisplayImage(NDTiffStorage.java:447)
                                   [       ]   at org.micromanager.magellan.internal.magellanacq.MagellanAcqUIAndStorage.getImageForDisplay(MagellanAcqUIAndStorage.java:306)
                                   [       ]   at org.micromanager.ndviewer.internal.gui.ImageMaker.getDisplayImage(ImageMaker.java:81)
                                   [       ]   at org.micromanager.ndviewer.internal.gui.ImageMaker.makeOrGetImage(ImageMaker.java:146)
                                   [       ]   at org.micromanager.ndviewer.main.NDViewer$DisplayImageComputationRunnable.run(NDViewer.java:895)
                                   [       ]   at org.micromanager.ndviewer.internal.gui.CoalescentExecutor$3.run(CoalescentExecutor.java:124)
                                   [       ]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                                   [       ]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 43 [Acquisition image processing and saving thread] WAITING
                                   [       ]   at sun.misc.Unsafe.park(Native Method)
                                   [       ]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
                                   [       ]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
                                   [       ]   at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)
                                   [       ]   at org.micromanager.acqj.main.Acquisition.lambda$startSavingExecutor$1(Acquisition.java:210)
                                   [       ]   at org.micromanager.acqj.main.Acquisition$$Lambda$220/1274681054.run(Unknown Source)
                                   [       ]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                                   [       ]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 44 [Overalyer task thread] WAITING
                                   [       ]   at sun.misc.Unsafe.park(Native Method)
                                   [       ]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
                                   [       ]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
                                   [       ]   at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 46 [Submitted sequence monitor] WAITING
                                   [       ]   at sun.misc.Unsafe.park(Native Method)
                                   [       ]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
                                   [       ]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
                                   [       ]   at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 47 [Acq Eng event generator] WAITING
                                   [       ]   at sun.misc.Unsafe.park(Native Method)
                                   [       ]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
                                   [       ]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
                                   [       ]   at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 48 [Acquisition Engine Thread] WAITING
                                   [       ]   at sun.misc.Unsafe.park(Native Method)
                                   [       ]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
                                   [       ]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
                                   [       ]   at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)
                                   [       ] Thread 49 [Magellan viewer communication thread] WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at java.lang.Object.wait(Object.java:502)
                                   [       ]   at java.awt.EventQueue.invokeAndWait(EventQueue.java:1315)
                                   [       ]   at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
                                   [       ]   at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
                                   [       ]   at org.micromanager.ndviewer.main.NDViewer.newImageArrived(NDViewer.java:365)
                                   [       ]   at org.micromanager.magellan.internal.magellanacq.MagellanAcqUIAndStorage$3.run(MagellanAcqUIAndStorage.java:201)
                                   [       ]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                                   [       ]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                                   [       ]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                   [       ]   at java.lang.Thread.run(Thread.java:748)

**Comment by henrypinkard** [comment]
https://github.com/micro-manager/micro-manager/pull/1734
