### ISSUE TITLE
mm2: Inspector histograms don't always show up until channel scrolled

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#174]
E.g. after opening a multi-channel dataset, sometimes only one histogram (or none at all) shows up. The rest show up when you scroll through the channels in the viewer window.

**Comment by ChrisWeisiger** [comment]
This is now fixed, and as a pleasant side effect I was able to fix the rare hang when starting an acquisition that we had been experiencing as well.
