### ISSUE TITLE
mm2: Histogram is colored even when Color Mode is Grayscale

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#176]
This just continues to confuse me.  Snap an image, set color mode to Grayscale (if it was not Grayscale already) and notice a red or blue (depending on color scheme) histogram.  This make it very hard to mentally associate that histogram with the image being displayed.  Can the histogram be shown in white when the color mode is Grayscale?

**Comment by ChrisWeisiger** [comment]
Done.
