### ISSUE TITLE
mm2 and mm1.4: One line beanshell script causes hard crash

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#178]
Start up Micro-Manager without loading a configuration file.  Execute the following line in the Beanshell interpreter:
`mm.core().initializeCircularBuffer();`
On my Mac, Micro-Manager disappears form the screen and offers to send a report to Apple.  The same crash happens in 1.4 (modify the line to work with the 1.4 syntax)

**Comment by marktsuchida** [comment]
Fixed in 1.4.x in SVN r15941. To be forward-ported to mm2.

**Comment by marktsuchida** [comment]
Fix merged into mm2 as part of PR #179.
