### ISSUE TITLE
Silent install of micro-manager from command line Windows

### ISSUE THREAD

**Issue by vikramcee** [micro-manager/micro-manager#1794]
Is it possible to silently install (without the GUI) the executable file on Windows?

To clarify, this for CI purposes so that pycro-manager code can be tested automatically on a fresh install

**Comment by nicost** [comment]
The installer on Windows is based on InnoSetup.  There appear to be command line options, see: https://jrsoftware.org/ishelp/index.php?topic=setupcmdline.  Try /VerySilent and see what happens.
