### ISSUE TITLE
Output empty image when start a new image acquisition session

### ISSUE THREAD

**Issue by NeversayEverLin** [micro-manager/micro-manager#1796]
Hi, I am trying to write a device adapter for Bit Flow frame grabber-based camera (Adimec). When I start the sequence acquisition at first time, it works great with expected image output. However, if I start a second or more sequence acquisition, the image output is always zeros. I though it was due to the initialization of circular buffer, then I do re-initialize the circular buffer at beginning of sequence acquisition, but the problem persists. 

My start sequence acquisition function call is:

`
 int BFCXP::StartSequenceAcquisition(long numImages, double interval_ms, bool stopOnOverflow)
     {

	if (IsCapturing())
		return DEVICE_CAMERA_BUSY_ACQUIRING;

	int ret = GetCoreCallback()->PrepareForAcq(this); //prepare actually do nothing 
	if (ret != DEVICE_OK)
		return ret;

	MM::MMTime startTime0 = GetCurrentMMTime();
	numImages_ = numImages; 
	interval_ms_ = interval_ms; 
	stopOnOverflow_ = stopOnOverflow; 
	img_ = ImgBuffer(); //re-initialize the MM circular buffer. 
	ResizeImageBuffer(); 
	
	// Allocate memory for camera buffers 
	//BufArray.BufferMem: BufArray is the buffer array for camera; 
	Error = BiBufferAllocCam(hBoard, &BufArray, numImages_);
	//Error = BiBufferAlloc(hBoard, &BufArray, GetImageWidth(), GetImageHeight(), bitDepth_, numImages); 
	if (Error != BI_OK)
	{
		LogMessage("Error on BiBufferAllocCam");
		BiErrorShow(hBoard, Error);
		BiBrdClose(hBoard);
		return 1;
	}

	//Get the array of buffer pointers that have been generated by BiCamAlloc; Buffer array must be re-assigned to pBufferArray
	BiBufferArrayGet(hBoard, &BufArray, &pBufferArray);

	// Setup for sequence capture 
	Error = BiSeqAqSetup(hBoard, &BufArray, AqSetupOptions);
	if (Error != BI_OK)
	{
		LogMessage("Error on BiSeqAqSetup");
		BiErrorShow(hBoard, Error);
		BiBufferFree(hBoard, &BufArray);
		BiBrdClose(hBoard);
		return 1;
	}

	// Setup Sequence acquire parameters 
	Error = BiSeqParameters(hBoard, &BufArray, StartFrame, numImages_, SkipFrames);
	if (Error != BI_OK)
	{
		LogMessage("Error on BiSeqParameters");
		BiErrorShow(hBoard, Error);
		BiSeqCleanUp(hBoard, &BufArray);
		BiBufferFree(hBoard, &BufArray);
		BiBrdClose(hBoard);
		return 1;
	}

	//DEBUG
	auto begin = std::chrono::high_resolution_clock::now();

	Error = BiSeqControl(hBoard, &BufArray, BISTART, BiWait);
	if (Error != BI_OK)
	{
		if (Error < BI_WARNINGS)
		{
			LogMessage("Error on BiSeqControl");
			BiErrorShow(hBoard, Error);
			BiSeqCleanUp(hBoard, &BufArray);
			BiBufferFree(hBoard, &BufArray);
			BiBrdClose(hBoard);
			return 1;
		}
	}

	// Wait here until the sequence has been captured.
	while (WaitReturn)
	{
		WaitReturn = BiSeqWaitDone(hBoard, &BufArray, 20000);
	}
	// 

	// DEBUG: Verify that all frames have been captured and no frames have been missed.
	auto end = std::chrono::high_resolution_clock::now();
	auto elapsed = std::chrono::duration_cast<std::chrono::nanoseconds>(end - begin);

	acqStr_ = "Acquisitoin Frame Rate is measured as ";
	acqStr_ += std::to_string((double)numImages / ((double)(elapsed.count() * 1e-9)));
	acqStr_ += " Hz";
	LogMessage(acqStr_);

	Error = BiCaptureStatusGet(hBoard, &BufArray, &FramesCaptured, &FramesMissed);
	if (Error != BI_OK)
	{
		LogMessage("Error on BiCaptureStatusGet!");
	};

	//start thread 
	sequenceStartTime_ = GetCurrentMMTime();
	imageCounter_ = 0;
	thd_->Start(numImages, interval_ms);
	stopOnOverFlow_ = stopOnOverflow;
       return DEVICE_OK
}
`
And the thread function calls like: 
`
void BFCXP::OnThreadExiting() throw()
{
	//LogMessage("Call thread exiting!!!");
	try
	{
		LogMessage(g_Msg_SEQUENCE_ACQUISITION_THREAD_EXITING);
		GetCoreCallback() ? GetCoreCallback()->AcqFinished(this, 0) : DEVICE_OK;	
		
		// Clean things up 
		Error = BiSeqCleanUp(hBoard, &BufArray);
		if (Error != BI_OK)
			BiErrorShow(hBoard, Error);

		Error = BiBufferFree(hBoard, &BufArray);
		if (Error != BI_OK)
			BiErrorShow(hBoard, Error);
	}
	catch (...)
	{
		LogMessage(g_Msg_EXCEPTION_IN_ON_THREAD_EXITING, false);
	}
};
`

`
int BFCXP::RunSequenceOnThread()
{
	int ret = DEVICE_ERR;
	//MM::MMTime startTime = GetCurrentMMTime();
	//acqStr_ = "thread run on ";
	//acqStr_ += std::to_string(imageCounter_);
	//LogMessage(acqStr_);
	// Start Sequence Acquisition 
	//printf("Starting Acquisition\n");
	//while ((GetCurrentMMTime() - startTime).getMsec() < exposure_ms_)
	///{
		//CDeviceUtils::SleepMs(1);
	//}

	ret = InsertImage();

	if (ret != DEVICE_OK)
	{
		return ret;
	}
	return ret;
};`

`
int BFCXP::InsertImage()
{
	MM::MMTime timeStamp = this->GetCurrentMMTime();
	char label[MM::MaxStrLength];
	this->GetLabel(label);

	memcpy((void*)img_.GetPixels(), pBufferArray[imageCounter_], (std::string::size_type)img_.Width() * img_.Height() * GetImageBytesPerPixel());

	// Important:  metadata about the image are generated here:
	Metadata md;
	md.put("Camera", label);
	md.put(MM::g_Keyword_Elapsed_Time_ms, CDeviceUtils::ConvertToString((timeStamp - sequenceStartTime_).getMsec()));
	md.put(MM::g_Keyword_Metadata_ROI_X, CDeviceUtils::ConvertToString((long)roiX_));
	md.put(MM::g_Keyword_Metadata_ROI_Y, CDeviceUtils::ConvertToString((long)roiY_));

	imageCounter_++; //on increase the index 

	char buf[MM::MaxStrLength];
	GetProperty(MM::g_Keyword_Binning, buf);
	md.put(MM::g_Keyword_Binning, buf);

	MMThreadGuard g(imgPixelsLock_);

	//const unsigned char* pI;
	const unsigned char* pI = GetImageBuffer();

	unsigned int w = GetImageWidth();
	unsigned int h = GetImageHeight();
	unsigned int b = GetImageBytesPerPixel();

	int ret = GetCoreCallback()->InsertImage(this, pI, w, h, b, nComponents_, md.Serialize().c_str());
	if (!stopOnOverFlow_ && ret == DEVICE_BUFFER_OVERFLOW)
	{
		// do not stop on overflow - just reset the buffer
		GetCoreCallback()->ClearImageBuffer(this);
		// don't process this same image again...
		return GetCoreCallback()->InsertImage(this, pI, w, h, b, nComponents_, md.Serialize().c_str(), false);
	}
	else
	{
		return ret;
	}
}
`

Am I supposed to do other re-initialize to make MM clear its circular buffer? Thanks!

**Comment by nicost** [comment]
I don't think the circular buffer is the problem.  I believe that the only way images with all zeros can be retrieved from the circular buffer is when they first were inserted there.  Just to be sure, how are you checking the images?

B.t.w., it looks like your code is waiting until the whole sequenced has been retrieved by the Bitflow card, then transfers the images one by one.  Usually, we try to insert the images into the circular buffer as soon as they are available.

Did you have a look at the "TwoPhoton" adapter code?  It uses a Bitflow card as well, and may (or may not) be directly usable to you (or at least provide inspiration).
