### ISSUE TITLE
mm2: DisplayWindow status line shows false positions name

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#180]
Steps to reproduce: 
- Using the demo-configuration run a MDA that includes multiple positions
- Move the p slider in the displaywindow and note that the name for the position in the display window does not change (even though the position name in the Image metadata does change), resulting in the wrong position name for the image shown.

Kind of related: the status line does not display the channel name, even though that would be quite useful in non-composite modes.

**Comment by ChrisWeisiger** [comment]
This has been fixed; thanks for the bug report. I've also added the channel name to the status line.
