### ISSUE TITLE
Support for Windows 11

### ISSUE THREAD

**Issue by ckolluru** [micro-manager/micro-manager#1818]
Do the nightly builds support Windows 11 OS? 

It seemed to work for me for a while, but now the application quits when I try to load a hardware configuration.

Thanks!

**Comment by nicost** [comment]
Yes they do (at least, we have been using it on Windows 11 here).  Most likely, there is a problem in the hardware configuration. 

Try starting without a config file, go to` Help >  Create a Problem Report` start the report, then load your config file.  If that does not help you solve the issue, post the output on https://image.sc (tag with "Micro-Manager").

**Comment by chaitanya-kolluru-elucid** [comment]
Thanks for showing the logging mechanism, it was quite useful. 

Turns out it crashes when loading Spinnaker for which I had the wrong version installed (it needs 2.3.0.77 specifically as mentioned in the documentation, my bad!)

**Comment by ckolluru** [comment]
Thanks for showing the logging mechanism, it was quite useful.

Turns out it crashes when loading Spinnaker for which I had the wrong version installed (it needs 2.3.0.77 specifically as mentioned in the documentation, my bad!)
