### ISSUE TITLE
mm2 metadata only display values that change between two images

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#182]
In mm 1.4, all per-image metadata are shown (without checking the "Show unchanging properties" checkbox) that change within the dataset.  In 2.0, only the metadata that differ with respect to the previously shown image are shown.  In my opinion, the 1.4 behavior is highly desired, and the 2.0 behavior makes the metadata display confusing and close to useless.  A compounding problem is that the metadata table can not be resized by the user, therefore looking at all metadata is cumbersome.

**Comment by ChrisWeisiger** [comment]
This is now fixed, and the Metadata Panel has been made larger.

**Comment by nicost** [comment]
Thanks!  Amazing turn around!
