### ISSUE TITLE
Feature request: display MM menu when MM windows are selected

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#183]
Currently, when a selecting any window other than the main Micro-Manager window, no menu is shown (actually, when selecting an image viewer, the ImageJ menu is shown),  Therefore, when the user wants to make another menu selection, she needs to first click on the main Micro-Manager window to make the menu re-appear.  Would it be possible to show the Micro-Manager menu when any of the Micro-Manager windows are active (other than the viewer)?  This is probably only a problem on the Mac (with its central menu rather than window-bound menu).

**Comment by ChrisWeisiger** [comment]
This has now been implemented; on OSX you'll get the µManager menubar on any non-image window. On Windows we have the existing behavior. Any frame that wants to have a copy of the µManager menubar at the top can use `setJMenuBar(org.micromanager.internal.menus.MMMenuBar.createMenuBar(MMStudio studio))`
