### ISSUE TITLE
maven artifact contents

### ISSUE THREAD

**Issue by pedro-w** [micro-manager/micro-manager#1835]
I was looking for place where MMCoreJ can be accessed using maven. I found it [here](https://central.sonatype.com/artifact/org.micro-manager.mmcorej/MMCoreJ/versions) on maven central but the newest version 10.4.0 is missing a lot of classes that are in 10.1.1.0 specifically it has the `mmcorej.org.json` package but not the `mmcorej` package.

(hopefully this is the correct place to ask about this)

[edit] there are other entries listed on the Scijava repo but they don't have any jars associated with them - org.micro-manager vs org.micromanager ?
https://maven.scijava.org/#nexus-search;quick~mmcorej

**Comment by henrypinkard** [comment]
The MMCoreJ on maven central is not an automated or up to date version. We manually uploaded that there, for the purposes of being able to automatically build the components that depend on it that are in separate repos with Mavenized build systems (e.g. the java acquisition engine). It only gets updated when a new feature gets added to the core that these components need

Longer term, the plan is to have all of the components building with maven (https://github.com/micro-manager/micro-manager/issues/1392)


> [edit] there are other entries listed on the Scijava repo but they don't have any jars associated with them - org.micro-manager vs org.micromanager ?
> https://maven.scijava.org/#nexus-search;quick~mmcorej

I suspect these are leftover from when we were initially trying different ways to set this up.

The best way to get an up to date MMCoreJ is to download a nightly build and pull it out, or to build it yourself
