### ISSUE TITLE
Usability: Snap automatically after using buttons to change the ROI

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#1859]
Whenever I use one of the ROI buttons, I always directly Snap an image to check if the ROI is where I want it.  I can nor really imagine a use of these ROI buttons where you would not want an image snapped right away.  Snapping automatically seems a nice convenience to me.  Any reasons against?

**Comment by marktsuchida** [comment]
I agree it makes sense for the majority of users and I would have nothing against it if it is switchable in Options.

There are occasionally people who use MM for experiments involving very long exposures (or slow scans). For these people, it may be nice if it is possible to click on any of the 3 buttons without snapping an image.
