### ISSUE TITLE
mm2: Tab labels are very hard to read in Night mode

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#187]
This is most easily seen in the Projector plugin.  It is almost impossible to read the Tab labels of the plugin.  The ASIdiSPIM plugin suffers from the same problem.  Is this something that needs to be handled in the TabbedPanes themselves or in the code setting the Night theme?

**Comment by ChrisWeisiger** [comment]
This is fixed now; I've removed JTabbedPane from the list of component types that get updated when the day/night mode is set, so they should always have their default coloration (their contents, however, will still be updated; this only appears to change the rendering of the tabs themselves). Thanks for the report.
