### ISSUE TITLE
Deskew on-the-fly processor doesn't allow MDA to save data

### ISSUE THREAD

**Issue by fadero** [micro-manager/micro-manager#1871]
If I have the Deskew processor enabled while I am running an MDA, the deskew plugin functions correctly. However, the MDA doesn't save any of the raw data to disk. The MDA makes a folder for the data but does not write .tifs to it. 

I have tried enabling "Keep Original," and I have also tried switching from "Hold in RAM" to "Live." In any configuration, it seems that having deskew "Enabled" during an MDA prevents raw data saving. 

The raw data never appears in the acquisition window, which may have something to do with the issue.

**Comment by nicost** [comment]
This also works correctly with the demo configuration.  Mysterious..
