### ISSUE TITLE
Split View Plugin is broken in latest nightly builds

### ISSUE THREAD

**Issue by dickinson-lab** [micro-manager/micro-manager#1874]
We recently replaced a computer and installed the latest version of micro-manager.  Since upgrading to the Jan. 9 MM build, the SplitView plugin no longer works. When enabling the processor for live images, we see the error message 

"Error: An error occurred while processing images. 
The size of this image differs from previous image(s)."  

and no image is displayed.  

Maybe related to other recent issues with on-the-fly processors?  #1842 #1844

**Comment by nicost** [comment]
Sorry about that.  Should be fixed in tonight's build (#1876).

**Comment by dickinson-lab** [comment]
Thanks Nico!
