### ISSUE TITLE
Request for new autofocus plugin

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#1905]
While discussing code needed for lightsheet microscopes, we realized there is a need for a new aufocus plugin in Micro-Manager that has some of the capabilities of the diSPIM plugin in 1.4.  

Desired features are:
- It should be a superset of the Oughtafocus plugin, in addition it should:
- allow setting the z-stage to use for focusing (which can be different from the core-focus drive)
- Optionally run a Z-stack and interpret this after the fact rather than run a Brant optimizer.  In this mode, it should run a sequence if the hardware allows it (this could most easily be done using the acquisition engine), and display a focus quality curve if requested

Optional: the code could be structured such that it could accept a DataStore and provide a focus score per image in the store.  

Also see the Image Sharpness pane in the Inspector window.

Name?

**Comment by fadero** [comment]
These features requests sound reasonable.

Unsure of a name. Some suggestions:

- Focus Stack
- Sharp Focus
- Focal Sweep

**Comment by jondaniels** [comment]
I'm not picky as to the name.

Do you see this standing alongside OughtaFocus (and use the same scoring algorithms) or would it be augmenting OughtaFocus with some additional properties to choose whether to do the iterative algorithm or the stack + fit algorithm?

**Comment by bls337** [comment]
I think the autofocus graph in the diSPIM plugin looks nice, it may be worth reusing some of the code. It has the code for curve-fitting in there too.
