### ISSUE TITLE
Multi-channel images don't display correctly when saving as NDTiff

### ISSUE THREAD

**Issue by dickinson-lab** [micro-manager/micro-manager#1923]
I am using the latest (4/9/24) nightly build to acquire images with many timepoints, 10 z planes and 2 channels. Since these stacks end up rather large I decided to try saving as NDTiff.  However, only the first channel is shown in the image window that is displayed during acquisition.  The second channel is all black in the image display window and shows only 0 values in the histogram window.  The data saved to disk are correct, but this still poses an issue since the user cannot see what is happening with the acquisition in real time. 
![NDTiff](https://github.com/micro-manager/micro-manager/assets/14065006/b8c07865-be64-4fb9-a83a-0421b1fd49cf)

Oddly, if I stop the acquisition, leave the NDTiff window open and perform a second acquisition saving as Image Stack, the NDTiff display is now corrected.  I'm mentioning this in case it helps diagnose the issue.

**Comment by nicost** [comment]
I believe this is due to the following code in NDTiffAdapter:


```
/**
    * This implementation only check for an exact match. It does not actually return a list
    * of all images that match the given coordinates, as I am not quite sure how to implement that.
    *
    * @param coords Coordinates specifying images to match
    * @return List of images matching the coordinates
    * @throws IOException can always happen.
    */
   @Override
   public List<Image> getImagesMatching(Coords coords) throws IOException {
      List<Image> imageList = new LinkedList<>();
      if (storage_ == null) {
         return imageList;
      }
      HashMap<String, Object> ndTiffCoords = coordsToHashMap(coords);
      if (storage_.hasImage(ndTiffCoords)) {
         TaggedImage ti = addEssentialImageMetadata(storage_.getImage(ndTiffCoords), ndTiffCoords);
         Image img = new DefaultImage(ti, hashMapToCoords(ndTiffCoords),
                 studioMetadataFromJSON(ti.tags));
         imageList.add(img);
      }
      return imageList;
   }

   @Override
   public List<Image> getImagesIgnoringAxes(
           Coords coords, String... ignoreTheseAxes) throws IOException {
      // This is obviously wrong, but not quite sure what to do at this point....

      return getImagesMatching(coords);
   }
```

Problem is, I am not sure how to do this.  Perhaps the only way is to set up a shadow list with coordinates in the adapter code and not rely on NDTiff storage for this.  That is quite an ugly approach.  The other approach would be to dive into the NDTiff storage code...
