### ISSUE TITLE
Feature request: enable focus maintenance during MDA z-stack

### ISSUE THREAD

**Issue by fadero** [micro-manager/micro-manager#1937]
I'd like to request a feature where a focus maintenance device (e.g. ASI's CRISP, Nikon's PFS) is allowed to remain enabled during an MDA with a z-stack. Currently, the MDA disables the focus maintenance device.

I'm asking for this because the core focus I'm using (galvo mirror) is not the same device that is maintaining focus (ASI FTP with CRISP). So I'd like to keep the CRISP continuously active while my galvo mirror moves.

@nicost

**Comment by nicost** [comment]
Implemented in #1938, use: `mm.settings().setUnlockAutofocusDuringZStack(false)`.
