### ISSUE TITLE
New AcqEngJ does not return to initial position after MDA

### ISSUE THREAD

**Issue by fadero** [micro-manager/micro-manager#1946]
@nicost When I set my z-stage to 0 and the run a z-stack MDA (ex. -10 to +10), my stage stops at -10 instead of 0 after the acquisition finishes. 

Is there any way that we can have the AcqEngJ execute a "return to starting position" behavior at the end of the MDA?

**Comment by fadero** [comment]
Bumping this for @nicost to take a look at. Luckily, it doesn't seem to start the next MDA at a different location, but snap and live after an MDA display the "end" location in the z stack, rather than returning to the middle.

**Comment by marktsuchida** [comment]
Looks like #1993 closes this; please reopen if not.

**Comment by nicost** [comment]
Thanks, sorry, forgot to close this at the same time.
