### ISSUE TITLE
micro-manager - Zeiss CAN29 download

### ISSUE THREAD

**Issue by nicoseyda** [micro-manager/micro-manager#1959]
Hello,

I just downloaded micromanager 2.0 and it doesnt recognize my Zeiss Axio Observer. It seems it needs the CAN29 adapter, where can I find it for download ?

Thanks!

**Comment by nicost** [comment]
The Zeiss CAN 29 adapter is included in the binary distribution.  Its name is `mmgr_dal_ZeissCAN29.dll`.  

If you would like help configuring your microscope it is better to post questions on https://image.sc.
