### ISSUE TITLE
Controlling Ni cards with micro manager

### ISSUE THREAD

**Issue by altuntasumut** [micro-manager/micro-manager#1974]
Hello,

I have a Nikon eclipse microscope, and I am using micro manager to take 2D images.

I am doing a fatigue experiment and I want to take pictures with a micro-manager for every 10 cycles. I drive a stepper motor with NI cards. How can I send a signal to micro-manager to take 2D images?

Or can I write a code in the script panel in the micro manager to drive the stepper motor and take images for every 10 cycles?

Thank you.

**Comment by marktsuchida** [comment]
I don't know much about using NI cards for stepper motors (Micro-Manager does not have this capability), but one possibility would be to configure the NI card (or the software controlling it) to emit a separate digital pulse every 10 cycles (if it has that capability), outside of Micro-Manager. If your camera has a trigger input port, then you could configure the camera to take an image when it receives the pulse. (In Micro-Manager, you would set the external trigger properties appropriately, and run an acquisition with timepoints only, setting the interval to 0.) Whether this idea will work depends on the capability of the NI card and camera.

You might try asking your question on [forum.image.sc](https://forum.image.sc), our official support channel (with tag micro-manager), where it will be seen by more people. It would help to provide the model numbers of your NI card and camera, and a rough idea about the time scales involved (e.g., how long does a cycle take).
