### ISSUE TITLE
MDA Test Acquistition in MM 2.0.3_20241113 reports wrong channel names in inspect window

### ISSUE THREAD

**Issue by RobMesman** [micro-manager/micro-manager#2027]
When taking an image with test-acquisition in MDA the inspect image window reports the channel names used in the last saved acquire image instead of using the names of the channel that were selected, see also:
[https://forum.image.sc/t/mda-test-acquistition-issues-in-mm-2-0-3-20241113/105254](url)

**Comment by nicost** [comment]
Fixed in #2028
