### ISSUE TITLE
mm2: No user feedback upon Autofocus fullfocus error

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#203]
To reproduce this, it is easiest to modify the code of one of the java autofocus plugins to immediately throw a MMException in the fullfocus() method.  When running fullfocus in the UI (by clicking the binocular icon), no feedback is given to the user that anything went wrong.  It seems useful to know that something failed and to have a clue about what that may be (for instance, changing the parameters of the autofocus method could possibly help).

**Comment by ChrisWeisiger** [comment]
Done.
