### ISSUE TITLE
mm2: Inspector window now shows gaps for inactive InspectorPanel plugins

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#212]
Whereas before the latest (really awesome!) re-work of the Inspector Window there was no entry for the ClearVolume plugin before it was selected, there now is a gap where the "tab" for that plugin will appear, even when the plugin is not active.  This likely will happen with any other Inspector Panel plugin.  Not a big deal, but not as pretty as before.

**Comment by ChrisWeisiger** [comment]
This is now fixed; thanks for the report.
