### ISSUE TITLE
mm2: Multi-Dimensional Acquisition Window looks strange on Windows

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#223]
Especially in the Z-stacks section, there is no space between the start, end, and set size boxes.  This is on Windows 7, using Java 1.8.0_73.  Same thing with the nightly build and Java 6.

![clipboard](https://cloud.githubusercontent.com/assets/2153771/13337911/0cfa9e28-dbd3-11e5-98be-b7064852e42a.png)

**Comment by ChrisWeisiger** [comment]
This should be significantly improved now. Thoughts?

**Comment by marktsuchida** [comment]
I have created a patch that fixes several remaining issues (incorrect resizing behavior, lack of scrolling in comments area, inconsistent horizontal positioning of upper panel items, inconsistent capitalization and label alignment, etc.).
Yes, the channel table resizes now!
I still need to test on Windows before merging, just letting you know so there's no duplication of effort.

**Comment by marktsuchida** [comment]
Created PR #225 - tested on Windows and OS X.
