### ISSUE TITLE
mm2: Live display stops updating after a while

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#226]
Start live mode (Andor Zyla, ~10ms exposure time).  After a couple of minutes, the display stops updating.  Stopping and starting live mode again does not restore the display.  Closing the window and pressing live again restarts the live display, suggesting this is an issue in the display rather than the hardware.

**Comment by ChrisWeisiger** [comment]
Sorry, refresh my memory: is this still an issue? I know I've fixed some live stuff in the past few weeks, but I forget if this was one of them.

**Comment by nicost** [comment]
I think that you fixed this partly on 3/4/2016 
(https://github.com/micro-manager/micro-manager/commit/570f30fccc3764bfc3e8d841756399db9571d0c3), 
and then more fully on 3/7/2016 
(https://github.com/micro-manager/micro-manager/commit/b4e4a6c5836e9544976dbc45b8981622dc09ddde). 
Those appear to have resolved the issue.

**Comment by ChrisWeisiger** [comment]
Great, thanks!
