### ISSUE TITLE
mm2 opens single channel images always in color mode

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#233]
When opening single channel images saved on disk, they always appear in color mode, even when they were saved while being shown in greyscale, and even when other single channel image were already switched to greyscale.  In general, it is very difficult to convince MM 2.0 to show images in greyscale rather than as blue images (which even is the default when snapping images with a single camera).

**Comment by ChrisWeisiger** [comment]
Should be fixed now. Thanks for the report.
