### ISSUE TITLE
micromanager starting script on Linux

### ISSUE THREAD

**Issue by kbellve** [micro-manager/micro-manager#253]
On Linux, last line of the micromanager script launches org.micromanager.MMStudio but the class appears to be org.micromanager.**internal**.MMStudio, at least the way it is defined in MMJ_.jar

This does not work:
`/usr/lib/jvm/java/bin/java -Xmx1024M \
   -XX:MaxDirectMemorySize=1000G \
   -classpath "$CLASSPATH" \
   -Dmmcorej.library.loading.stderr.log=yes \
   -Dmmcorej.library.path="/usr/local/lib/micro-manager" \
   -Dorg.micromanager.plugin.path="/usr/local/share/micro-manager/mmplugins" \
   -Dorg.micromanager.autofocus.path="/usr/local/share/micro-manager/mmautofocus" \
   -Dorg.micromanager.default.config.file="/usr/local/share/micro-manager/MMConfig_demo.cfg" \
   -Dorg.micromanager.corelog.dir=/tmp \
   org.micromanager.MMStudio
`

This works:

`/usr/lib/jvm/java/bin/java -Xmx1024M \
   -XX:MaxDirectMemorySize=1000G \
   -classpath "$CLASSPATH" \
   -Dmmcorej.library.loading.stderr.log=yes \
   -Dmmcorej.library.path="/usr/local/lib/micro-manager" \
   -Dorg.micromanager.plugin.path="/usr/local/share/micro-manager/mmplugins" \
   -Dorg.micromanager.autofocus.path="/usr/local/share/micro-manager/mmautofocus" \
   -Dorg.micromanager.default.config.file="/usr/local/share/micro-manager/MMConfig_demo.cfg" \
   -Dorg.micromanager.corelog.dir=/tmp \
   org.micromanager.internal.MMStudio
`

**Comment by ChrisWeisiger** [comment]
Thanks for the report. I've fixed this and another (as far as I can tell harmless) reference to `org.micromanager.MMStudio` in 74cade81c846c4a3533479dc438a7644e6fb59c1. I lack a Linux machine to test the launch on; please re-open this issue if the fix doesn't work.
