### ISSUE TITLE
Binning and Dual Camera with MDA

### ISSUE THREAD

**Issue by kbellve** [micro-manager/micro-manager#255]
Looks like the MDA window is trying to set the binning of the dual cameras, which is not allowed with Nico's virtual Dual Camera device. Binning defaults to "0" when you initialize with Dual Camera as your main camera. Not an issue when snapping or live imaging. If I set Dual Camera to 1x1 binning I get an error "Cannot set property Binning..."

But if I set Binning to 1x1 with a single camera, and then switch back to Dual Cameras (which then takes the 1x1 binning), then the MDA doesn't generate the error below:

> [ERR,Core:dev:Dual Andor] Cannot set property "Binning" to "0" [ Error in device "Dual Andor": Invalid property value: Binning (3) ]
> 2016-04-15T15:25:24.794881 tid140588823332608 [IFO,App] 
>                                               [       ] java.lang.RuntimeException: java.lang.Exception: Cannot set property "Binning" to "0" [ Error in device "Dual Andor": Invalid property value: Binning (3) ] in Thread[AcquisitionEngine2010 Thread (Clojure),6,main]

**Comment by nicost** [comment]
The virtual Dual Camera Device (MultiCamera) does let the user set binning.  It will display binning "0" when the binning settings of the "slave" camera differ.  Setting binning of the MultiCamera will set binning of all "slave" cameras.  This works correctly with the DemoCamera and MultiCamera.  When the lab re-opens, I'll test this with a Dual Andor setup.  Closing for now, but please re-open if it is still a problem (and then it most likely is in the Andor device adapter).
