### ISSUE TITLE
mm2: 32bit MM build are broken

### ISSUE THREAD

**Issue by hadim** [micro-manager/micro-manager#273]
When I try to launch MM I have this message : "ImageJ.exe is not a valid Win32 application". I guess something went wrong when you recently replaced the launcher.

**Comment by ChrisWeisiger** [comment]
Can confirm, though the error message is different on our 64-bit system; it launches fine but isn't able to load the 32-bit libraries. My mistake for updating to the 64-bit launcher. Should be fixed now, though it'd be good to now check up on issue #256 which the launcher update was originally intended to fix.

Please confirm if this issue can be closed.

**Comment by hadim** [comment]
I confirm the fix. (the IJ icon does not show anymore on the .exe, not a big deal...).
