### ISSUE TITLE
DataManager.createMultipageTIFFDatastore overwrites existing data without prompting

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#298]
Running something like the below scripts twice results in the first data-set to be over-written on the second try.  I did not expect that behavior.  Is this indeed the intent, and is it the caller's responsibility to make sure that the storage location did not yet exist?  If so, it would be good to add this to the documentation.

saveLocation = "/Users/nico/test/screen/test";

data = mm.data().createMultipageTIFFDatastore(saveLocation, true, false);
dw = mm.displays().createDisplay(data);
mm.displays().manage(data);

mm.getCMMCore().snapImage();
tImg = mm.getCMMCore().getTaggedImage();
c = mm.data().createCoords("t=0,p=0,c=0,z=0");
data.putImage(mm.data().convertTaggedImage(tImg, c, null));

mm.getCMMCore().snapImage();
tImg2 = mm.getCMMCore().getTaggedImage();
c2 = mm.data().createCoords("t=0,p=0,c=1,z=0");
data.putImage(mm.data().convertTaggedImage(tImg2, c2, null));

data.freeze();

**Comment by ChrisWeisiger** [comment]
Thanks for the bug report; this is absolutely a bug. We now throw an IOException if the user attempts to create a StorageMultipageTiff "on top of" an existing one. Users should use `DataManager.getUniqueSaveDirectory()` to get a directory name that is safe for saving to.
