### ISSUE TITLE
HCS plugin: Selection behavior incorrect

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#300]
When HCS Site Generator is in Select mode,
- a well can be selected by clicking on it
- a rectangular region can be selected by dragging over it
- a rectangular region can be added to the selection by dragging over it with CTRL pressed
- a single well can be removed from the selection by clicking it with CTRL pressed
- yet, a single well cannot be added to the selection by clicking it with CTRL pressed
- also, a rectangular region cannot be removed from the selection by dragging over it with CTRL pressed

**Comment by ChrisWeisiger** [comment]
This is now fixed.
