### ISSUE TITLE
HCS Plugin: Incorrect display and behavior after creating custom plate

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#301]
(1) After creating and saving a custom plate, the Plate Format popup still shows the previous selection.
Also, there are some incorrect (?) vertical and horizontal lines drawn on the plate area.

(Also, minor point: the "Create Custom" button should read "Create Custom...". And it could be moved into the Plate Format menu so that it is next to "Load Custom...")

(Another minor point: it would be nice if the filename of the custom plate were displayed as the plate format selection, instead of "Load Custom...", when in use.)

(2) Creating or loading a custom plate, then clicking on "Calibrate XY...", results in a file open dialog asking for the plate. It also happens when editing the Imaging Sites (Rows, Columns, Spacing). This should not happen.

**Comment by ChrisWeisiger** [comment]
This is now fixed.
