### ISSUE TITLE
mm2: Overlay UI improvements

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#307]
- It would be easier to have a checkbox to toggle show/hide of each overlay (so that one need not remove and re-add a scale bar when only wanting to temporarily hide it)
- Newly added overlays should remember last-used settings
- Pattern overlays should display current size in pixels,  and in micrometers when available

**Comment by ChrisWeisiger** [comment]
I forgot to tag this issue in commit 6285146, but these have now all been done.
