### ISSUE TITLE
mm2: Quick Access Panel does not automatically re-open upon restart

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#312]
Since the Quick Access Panel's function is to make it easy for novice users to work with MM, it will be hard to explain that they have to open it manually.  Can the Quick Access Panels that were open when the user quit MM be restored on re-opening the application? Or is that already supposed to happen, but somehow failed for me?

**Comment by ChrisWeisiger** [comment]
When configuring the Quick Access Panel, there's a dropdown menu to select whether it should open on launch.
