### ISSUE TITLE
mm2: Various texts are (almost) unreadable in night mode

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#313]
There are multiples of these, the most important are the read-only variables in the device/property browser and its derivatives (essential for me in pixel size calibrator), and the number next to the slider in the front panel in edit mode.

**Comment by ChrisWeisiger** [comment]
This should be substantially improved now. Can we close this issue, or are there areas that remain hard to read?

**Comment by ChrisWeisiger** [comment]
I'm going to assume this is now resolved. Please re-open if there are any extant hard-to-read texts.

**Comment by nicost** [comment]
The number next to the slider is still unreadable when the group is selected (which happens after moving the slider and letting go of it).

**Comment by ChrisWeisiger** [comment]
Okay, this should now be fixed. Closing again; please re-open if you find another place where text is hard to read.
