### ISSUE TITLE
mm2 Viewer: z slider lock lets user drag position only once

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#315]
Run a time-lapse of z-stacks acquisition (i.e. 100 time points, 5 s interval, 8 z slices), press the lock next to the z-slider once (so that it is black).  Move the slider to a new position.  After the next z-stack was acquired, the slider moves back to the "new position" as expected.  Move the slider again, and wait for a new z-stack.  The slider moves to position 1 (i.e. the first "new position"), not the last position the slider was dragged.  I see this on Windows with hardware and on the Mac with the demo equipment.

**Comment by ChrisWeisiger** [comment]
This should now be fixed.
