### ISSUE TITLE
mm2: Live mode breaks on errors when restarting

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#325]
To reproduce:

- Apply this patch to DemoCamera. It simulates an error upon starting (continuous) sequence acquisition with a small ROI.
```
--- a/DeviceAdapters/DemoCamera/DemoCamera.cpp
+++ b/DeviceAdapters/DemoCamera/DemoCamera.cpp
@@ -1017,6 +1017,8 @@ int CDemoCamera::SetAllowedBinning()
  */
 int CDemoCamera::StartSequenceAcquisition(double interval)
 {
+   if (img_.Width() < 500)
+      return 12345;
    return StartSequenceAcquisition(LONG_MAX, interval, false);            
 }
 
```
- Start Live
- While Live is running, click on the set-ROI-to-center-quad button
- (Live continues despite error and lack of new images)
- Click on the reset-ROI button
- (Garbage images are displayed, hard crash may occur)

**Comment by ChrisWeisiger** [comment]
This is now fixed.
