### ISSUE TITLE
mm2: Rename "Duplicate This Window"?

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#357]
In image display window Gear menu. To something like "New Window for This Dataset"?

Just because "Duplicate" connotes making a copy (ImageJ uses it for that meaning; cf. right-click on the image), even if we are saying "Window".

If we rename it to "New Window for This Dataset", we could also shorten "Open New Inspector Window" to "New Image Inspector" (which also unifies terminology with the Inspector's title bar).

**Comment by ChrisWeisiger** [comment]
This has been done; both options have been renamed.
