### ISSUE TITLE
Autostretch doesn't update all channels when changing Z in composite mode

### ISSUE THREAD

**Issue by kthorn** [micro-manager/micro-manager#359]
Open a dataset with multiple channels and multiple Z planes. Select the composite color mode, check autostretch, then change Z. The brightness for the selected channel is autoscaled but the other channels use the min/max display values from the initial Z plane. I'm not sure if this is intentional, but it is not what I expected. Unchecking and rechecking autostretch autoscales all channels in the new Z plane.

**Comment by ChrisWeisiger** [comment]
This has now been fixed. Thanks for the report.
