### ISSUE TITLE
ScriptPanel: Non-default users' scrtipt choices are not remembered

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#370]
Start MM using a profile other than the default user.  Add a script to the list in the left pane of the Script Panel.  Restart MM using the same profile as before.  See how the script previously added is not there.  Now start as the default user.  Add a script.  Upon restart, the script is still there, moreover the "other" user gets the list of scripts of the default user.

**Comment by ChrisWeisiger** [comment]
This has now been fixed. Please note that your "other" users will have inherited the shortcuts set by the default user in the profile, so the first time you launch they'll still remember the default user's scripts; however, future changes should apply normally.
