### ISSUE TITLE
mm2: "Example" plugin should be a good example

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#377]
Things to fix (in order of importance):
- The package should be `org.micromanager.plugins.example`
- The GUI should use MigLayout, not NetBeans `.form`
- Legacy variable name `gui_` should probably be `mm_` or `app_`
- Nothing seems to happen when "OK" button is clicked, despite the code that increments a counter (maybe display it in a JLabel?)
- An example of listening to `StartupCompleteEvent` might be nice
- More explanatory comments (since this is example code)

**Comment by ChrisWeisiger** [comment]
See also issue #296.

**Comment by ChrisWeisiger** [comment]
This has now been done.
