### ISSUE TITLE
Viewer gets confused after using a multi-camera device

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#39]
Use a multi-camera configuration.  Snap an image with the multi-camera device (that has two or more channels).  Viewer shows the expected number of channels.  Switch to a single camera.  Snap an image.  Viewer still shows the two or more channels.  Close the Snap/Live View window.  Snap an image.  Viewer still shows the two or more channels, not the single channel coming from our camera

**Comment by ChrisWeisiger** [comment]
Just to be clear, this is on the mm2 branch?

-Chris

**Comment by nicost** [comment]
Absolutely!

Does one need to indicate that somehow?  Isn't this repository all about 
the mm2 branch?

Best,

Nico

On 7/7/15 4:03 PM, ChrisWeisiger wrote:
> Just to be clear, this is on the mm2 branch?
>
> -Chris
>
> On Tue, Jul 7, 2015 at 3:34 PM, Nico Stuurman <notifications@github.com>
> wrote:
>
> > Use a multi-camera configuration. Snap an image with the multi-camera
> > device (that has two or more channels). Viewer shows the expected 
> number of
> > channels. Switch to a single camera. Snap an image. Viewer still 
> shows the
> > two or more channels. Close the Snap/Live View window. Snap an image.
> > Viewer still shows the two or more channels, not the single channel 
> coming
> > from our camera
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/micro-manager/micro-manager/issues/39>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/micro-manager/micro-manager/issues/39#issuecomment-119369800>.
>

-- 
Nico Stuurman
Vale lab, UCSF/HHMI
Genentech Hall, N316, MC2200
600 - 16th Street
San Francisco, CA 94158-2517
415 514 3927
nico.stuurman@ucsf.edu

**Comment by ChrisWeisiger** [comment]
Technically the repository has a copy of the master branch, even if it's
not necessarily up-to-date. And people could easily report 1.4 bugs here
instead of through other avenues, so I figure it's best to be explicit.

I'll take a look at this bug tomorrow. Sounds like the Snap/Live Manager
isn't properly recognizing when it needs to throw away its old datastore
and create a new one.

-Chris

**Comment by omsai** [comment]
>> Isn't this repository all about the mm2 branch?
>
> I figure it's best to be explicit.

Raised #40.

**Comment by ChrisWeisiger** [comment]
Fixed in commit e3cad32c.
