### ISSUE TITLE
Multi Camera channel names incorrect

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#407]
Incorrect channel names are used when running Snap or Live with Multi Camera.

**Comment by marktsuchida** [comment]
Probably as a result of this issue, previously used channel colors are not correctly applied.

**Comment by nicost** [comment]
Although it is not clear what the correct name should be, Snap/Live Multi-Camera channel names match the MDA Snap/Live Multi-Camera names since PR #751 

Previously used channel colors are still no applied, see issue #752
