### ISSUE TITLE
Display settings incorrect after switching back to Multi Camera

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#409]
Set display to Composite with dual camera. Switch to single camera (display settings get set to Grayscale). Switch back to dual camera. Display remains in Grayscale.

Possibly related to #407.

**Comment by nicost** [comment]
Currently, mode stays Composite throughout, which makes more sense to me than the automatic switching.  It would be nice to have a full definition of the desired Inspector/Display behavior when opening new displays/acquisitions, and/or changing imaging settings.
