### ISSUE TITLE
Autostretch is one image behind

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#41]
mm2 branch.  Using demo configuration, Auto-stretch switched on in the inspector.  Set exposure to 10 ms.  Snap an image.  Set exposure to 100 ms.  Snap an image and note that the image is completely white and that brightness/contrast were not updated in the inspector.  Snap another image.  Now the brightness/contrast are updated as expected.

**Comment by ChrisWeisiger** [comment]
Oh, right! Sorry for forgetting this one. Fixed in commit deec3216. Thanks for the report.
