### ISSUE TITLE
Projector: "Exposure" not honored when shutter used

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#416]
Seen with Andor Mosaic 3. When using the "Run ROIs now!" button or point-and-shoot mode, illumination turns on just momentarily, rather than for the Exposure duration.

The correct exposure is used if the illumination is TTL-controlled from the Mosaic (this happens asynchronously).

When shutter ("Phototargeting Shutter") is set, the shutter is closed immediately after displaying the SLM image, which does not wait for any exposure duration.

**Comment by nicost** [comment]
The Projector plugin has been massively re-worked in the intervening time, including shutter behavior.  If problems persist, open  new ticket.
