### ISSUE TITLE
Stale image in live mode

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#427]
When starting live mode, the first image shown is from a previous time live mode was run.  I can not reproduce this with the democamera (I tried hard!), but have seen it with Andor, Photometrics, and Hamamatsu cameras.  It is not a big deal, but it certainly is confusing to move the stage and see a first image from the old stage position.

**Comment by marktsuchida** [comment]
I've seen this, too.

**Comment by pskeshu** [comment]
I can reproduce this bug on an Andor Zyla and the latest windows nightly release. Any idea why this happens and what's the possible solution?

**Comment by nicost** [comment]
I have not run into this recently.  Re-open if it resurfaces.
