### ISSUE TITLE
Stage focus directions in Hardware Configuration Wizard are not remembered

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#443]
Set the focus direction to anything other than unknown, safe the configuration file and go through the HCW again.  See how there are always unknown.  Unless they are actually used somewhere it may b easiest to remove them.

**Comment by marktsuchida** [comment]
They are currently used by Henry's Magellan plugin only. But they should be remembered.

**Comment by nicost** [comment]
I no longer see this bug.  Not sure what changed, but closing since it is not reproducible.
