### ISSUE TITLE
Zooming using ImageJ magnifier tool does not size window correctly

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#444]
For example, use demo config to snap an image and compare behavior between the Micro-Manager +/- buttons and the left/right click with the magnifier tool.
With the latter, zooming out often results in extra gray margin in the window, and zooming in doesn't always enlarge the window enough.

**Comment by hadim** [comment]
I confirm this bug.

**Comment by marktsuchida** [comment]
The relevant code has since been rewritten and now behavior should be identical to the MM +/- buttons. (But see #925.)
