### ISSUE TITLE
multiple cameras using the different DeviceAdapter

### ISSUE THREAD

**Issue by raw476** [micro-manager/micro-manager#445]
Dear Micro-manager,

I have two camera: (1) Phtotmetrice Cascade II 512; (2) Hamamatsu ORCA-Flash4.0 V2. Can I use DeviceAdapter "multiple cameras" to record two images (not necessary to be synchronized) of two different cameras? Thanks for your help in advance!!

Many Thanks!

**Comment by marktsuchida** [comment]
This issue tracker is for bugs and concrete feature requests. Please use the mailing list for questions. (Paid support is also available from Open Imaging.)
