### ISSUE TITLE
MDA hang

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#458]
Regularly, running an MDA results in what appears to be a deadlock involving the EDT (i.e., Miro-Manager needs to be killed).  This only happens when using actual hardware and seems quite reproducible (until I tried to reproduce it;().

**Comment by BioinfoTongLI** [comment]
Hi, nicost,

First, thanks all the contributors for this super cool tools of microscopy.
I really enjoy using.

I confirm this bug. But with demo configuration also, not necessarily with actual hardware.
Sometimes rebooting MM solve the problem 
Sorry i didn' t look into detail the code. But it seems do a snap before live mode or MDA helps to reduce the possibility of hanging. 
Oh, yes. Live mode also hangs (tested on Mac, linux and windows)
I'm using the latest daily build. 
Develop environment : IntelliJ
Here is the error i got.

> [IFO,App] EDTHangLogger: Event handling has exceeded at least 1003 ms (currently 5504 ms since heartbeat timebase)
>                                               [       ] Stack traces follow (note: thread states queried later than stack traces)
>                                               [       ] Thread 2 [Reference Handler] WAITING
>                                               [       ]   at java.lang.Object.wait(Native Method)
>                                               [       ]   at java.lang.Object.wait(Object.java:503)
>                                               [       ]   at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)
>                                               [       ] Thread 3 [Finalizer] WAITING
>                                               [       ]   at java.lang.Object.wait(Native Method)
>                                               [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
>                                               [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
>                                               [       ]   at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)
>                                               [       ] Thread 4 [Signal Dispatcher] RUNNABLE
>                                               [       ] Thread 12 [RMI TCP Accept-0] RUNNABLE
>                                               [       ]   at java.net.PlainSocketImpl.socketAccept(Native Method)
>                                               [       ]   at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
>                                               [       ]   at java.net.ServerSocket.implAccept(ServerSocket.java:530)
>                                               [       ]   at java.net.ServerSocket.accept(ServerSocket.java:498)
>                                               [       ]   at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:399)
>                                               [       ]   at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:371)
>                                               [       ]   at java.lang.Thread.run(Thread.java:745)
>                                               [       ] Thread 13 [RMI Reaper] WAITING
>                                               [       ]   at java.lang.Object.wait(Native Method)
>                                               [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
>                                               [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
>                                               [       ]   at sun.rmi.transport.ObjectTable$Reaper.run(ObjectTable.java:351)
>                                               [       ]   at java.lang.Thread.run(Thread.java:745)
>                                               [       ] Thread 14 [GC Daemon] TIMED_WAITING
>                                               [       ]   at java.lang.Object.wait(Native Method)
>                                               [       ]   at sun.misc.GC$Daemon.run(GC.java:117)
>                                               [       ] Thread 15 [Java2D Disposer] WAITING
>                                               [       ]   at java.lang.Object.wait(Native Method)
>                                               [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
>                                               [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
>                                               [       ]   at sun.java2d.Disposer.run(Disposer.java:145)
>                                               [       ]   at java.lang.Thread.run(Thread.java:745)
>                                               [       ] Thread 17 [AWT-XAWT] RUNNABLE
>                                               [       ]   at sun.awt.X11.XToolkit.waitForEvents(Native Method)
>                                               [       ]   at sun.awt.X11.XToolkit.run(XToolkit.java:541)
>                                               [       ]   at sun.awt.X11.XToolkit.run(XToolkit.java:505)
>                                               [       ]   at java.lang.Thread.run(Thread.java:745)
>                                               [       ] Thread 18 [AWT-EventQueue-0] BLOCKED
>                                               [       ]   at org.micromanager.display.internal.DefaultDisplayWindow.setDisplayedImageTo(DefaultDisplayWindow.java:698)
>                                               [       ]   at org.micromanager.display.internal.DefaultDisplayWindow.requestRedraw(DefaultDisplayWindow.java:710)
>                                               [       ]   at org.micromanager.display.internal.DefaultDisplayWindow.setDisplaySettings(DefaultDisplayWindow.java:794)
>                                               [       ]   at org.micromanager.display.internal.DefaultDisplayWindow.setDisplaySettings(DefaultDisplayWindow.java:769)
>                                               [       ]   at org.micromanager.display.internal.LUTMaster.updateDisplayLUTForChannel(LUTMaster.java:319)
>                                               [       ]   at org.micromanager.display.internal.LUTMaster.initializeDisplay(LUTMaster.java:259)
>                                               [       ]   at org.micromanager.display.internal.CanvasUpdateQueue.showImage(CanvasUpdateQueue.java:333)
>                                               [       ]   at org.micromanager.display.internal.CanvasUpdateQueue.consumeImages(CanvasUpdateQueue.java:234)
>                                               [       ]   at org.micromanager.display.internal.CanvasUpdateQueue.access$000(CanvasUpdateQueue.java:71)
>                                               [       ]   at org.micromanager.display.internal.CanvasUpdateQueue$1.run(CanvasUpdateQueue.java:158)
>                                               [       ]   at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
>                                               [       ]   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
>                                               [       ]   at java.awt.EventQueue.access$300(EventQueue.java:103)
>                                               [       ]   at java.awt.EventQueue$3.run(EventQueue.java:706)
>                                               [       ]   at java.awt.EventQueue$3.run(EventQueue.java:704)
>                                               [       ]   at java.security.AccessController.doPrivileged(Native Method)
>                                               [       ]   at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
>                                               [       ]   at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
>                                               [       ]   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
>                                               [       ]   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
>                                               [       ]   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
>                                               [       ]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
>                                               [       ]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
>                                               [       ]   at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
>                                               [       ] Thread 19 [AWT-Shutdown] WAITING
>                                               [       ]   at java.lang.Object.wait(Native Method)
>                                               [       ]   at java.lang.Object.wait(Object.java:503)
>                                               [       ]   at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:296)
>                                               [       ]   at java.lang.Thread.run(Thread.java:745)
>                                               [       ] Thread 20 [DestroyJavaVM] RUNNABLE
>                                               [       ] Thread 22 [User profile save thread] TIMED_WAITING
>                                               [       ]   at java.lang.Thread.sleep(Native Method)
>                                               [       ]   at org.micromanager.internal.utils.DefaultUserProfile.runSaveThread(DefaultUserProfile.java:191)
>                                               [       ]   at org.micromanager.internal.utils.DefaultUserProfile.access$000(DefaultUserProfile.java:22)
>                                               [       ]   at org.micromanager.internal.utils.DefaultUserProfile$1.run(DefaultUserProfile.java:168)
>                                               [       ] Thread 23 [EDTHangLogger timer] RUNNABLE
>                                               [       ]   at java.lang.Thread.dumpThreads(Native Method)
>                                               [       ]   at java.lang.Thread.getAllStackTraces(Thread.java:1640)
>                                               [       ]   at org.micromanager.internal.diagnostics.EDTHangLogger.checkForHang(EDTHangLogger.java:233)
>                                               [       ]   at org.micromanager.internal.diagnostics.EDTHangLogger.access$200(EDTHangLogger.java:34)
>                                               [       ]   at org.micromanager.internal.diagnostics.EDTHangLogger$4.run(EDTHangLogger.java:220)
>                                               [       ]   at java.util.TimerThread.mainLoop(Timer.java:555)
>                                               [       ]   at java.util.TimerThread.run(Timer.java:505)
>                                               [       ] Thread 26 [Timer-0] TIMED_WAITING
>                                               [       ]   at java.lang.Object.wait(Native Method)
>                                               [       ]   at java.util.TimerThread.mainLoop(Timer.java:552)
>                                               [       ]   at java.util.TimerThread.run(Timer.java:505)
>                                               [       ] Thread 28 [Thread-4] TIMED_WAITING
>                                               [       ]   at java.lang.Object.wait(Native Method)
>                                               [       ]   at bsh.util.JConsole$BlockingPipedInputStream.read(Unknown Source)
>                                               [       ]   at java.io.PipedInputStream.read(PipedInputStream.java:378)
>                                               [       ]   at java.io.InputStream.read(InputStream.java:101)
>                                               [       ]   at bsh.util.JConsole.inPipeWatcher(Unknown Source)
>                                               [       ]   at bsh.util.JConsole.run(Unknown Source)
>                                               [       ]   at java.lang.Thread.run(Thread.java:745)
>                                               [       ] Thread 29 [BeanShell interpreter] TIMED_WAITING
>                                               [       ]   at java.lang.Object.wait(Native Method)
>                                               [       ]   at java.io.PipedInputStream.read(PipedInputStream.java:327)
>                                               [       ]   at java.io.PipedInputStream.read(PipedInputStream.java:378)
>                                               [       ]   at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
>                                               [       ]   at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
>                                               [       ]   at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
>                                               [       ]   at java.io.InputStreamReader.read(InputStreamReader.java:184)
>                                               [       ]   at bsh.JavaCharStream.FillBuff(Unknown Source)
>                                               [       ]   at bsh.JavaCharStream.ReadByte(Unknown Source)
>                                               [       ]   at bsh.JavaCharStream.readChar(Unknown Source)
>                                               [       ]   at bsh.JavaCharStream.BeginToken(Unknown Source)
>                                               [       ]   at bsh.ParserTokenManager.getNextToken(Unknown Source)
>                                               [       ]   at bsh.Parser.jj_ntk(Unknown Source)
>                                               [       ]   at bsh.Parser.Line(Unknown Source)
>                                               [       ]   at bsh.Interpreter.Line(Unknown Source)
>                                               [       ]   at bsh.Interpreter.run(Unknown Source)
>                                               [       ]   at java.lang.Thread.run(Thread.java:745)
>                                               [       ] Thread 32 [TimerQueue] WAITING
>                                               [       ]   at sun.misc.Unsafe.park(Native Method)
>                                               [       ]   at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
>                                               [       ]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
>                                               [       ]   at java.util.concurrent.DelayQueue.take(DelayQueue.java:209)
>                                               [       ]   at javax.swing.TimerQueue.run(TimerQueue.java:174)
>                                               [       ]   at java.lang.Thread.run(Thread.java:745)
>                                               [       ] Thread 33 [Thread-6] TIMED_WAITING
>                                               [       ]   at java.lang.Thread.sleep(Native Method)
>                                               [       ]   at org.micromanager.acquisition.internal.DefaultAcquisitionManager.executeAcquisition(DefaultAcquisitionManager.java:117)
>                                               [       ]   at org.micromanager.acquisition.internal.DefaultAcquisitionManager.runAcquisition(DefaultAcquisitionManager.java:73)
>                                               [       ]   at edu.univ_tlse3.acquisition.MAARS_mda.acquire(MAARS_mda.java:22)
>                                               [       ]   at edu.univ_tlse3.acquisition.SuperClassAcquisition.acquire(SuperClassAcquisition.java:55)
>                                               [       ]   at edu.univ_tlse3.acquisition.BuildSegAcqSetting.acquireToImp(BuildSegAcqSetting.java:74)
>                                               [       ]   at edu.univ_tlse3.maars.MAARS.run(MAARS.java:293)
>                                               [       ]   at java.lang.Thread.run(Thread.java:745)
>                                               [       ] Thread 34 [AcquisitionEngine2010 Thread (Clojure)] TIMED_WAITING
>                                               [       ]   at sun.misc.Unsafe.park(Native Method)
>                                               [       ]   at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
>                                               [       ]   at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
>                                               [       ]   at java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:384)
>                                               [       ]   at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
>                                               [       ]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>                                               [       ]   at java.lang.reflect.Method.invoke(Method.java:606)
>                                               [       ]   at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:92)
>                                               [       ]   at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:30)
>                                               [       ]   at org.micromanager.acq_engine$send_tagged_image.invoke(acq_engine.clj:486)
>                                               [       ]   at org.micromanager.acq_engine$collect_snap_image.invoke(acq_engine.clj:528)
>                                               [       ]   at org.micromanager.acq_engine$collect.invoke(acq_engine.clj:599)
>                                               [       ]   at org.micromanager.acq_engine$make_event_fns$fn__1292.invoke(acq_engine.clj:766)
>                                               [       ]   at org.micromanager.acq_engine$execute.invoke(acq_engine.clj:773)
>                                               [       ]   at org.micromanager.acq_engine$run_acquisition.invoke(acq_engine.clj:787)
>                                               [       ]   at org.micromanager.acq_engine$run$fn__1413.invoke(acq_engine.clj:976)
>                                               [       ]   at clojure.lang.AFn.run(AFn.java:24)
>                                               [       ]   at java.lang.Thread.run(Thread.java:745)
>                                               [       ] Thread 35 [Thread-7] TIMED_WAITING
>                                               [       ]   at java.lang.Thread.sleep(Native Method)
>                                               [       ]   at org.micromanager.display.internal.inspector.MetadataPanel.updateMetadata(MetadataPanel.java:262)
>                                               [       ]   at org.micromanager.display.internal.inspector.MetadataPanel.access$000(MetadataPanel.java:62)
>                                               [       ]   at org.micromanager.display.internal.inspector.MetadataPanel$1.run(MetadataPanel.java:107)
>                                               [       ]   at java.lang.Thread.run(Thread.java:745)
>                                               [       ] Thread 36 [Thread-8] TIMED_WAITING
>                                               [       ]   at java.lang.Thread.sleep(Native Method)
>                                               [       ]   at org.micromanager.display.internal.inspector.CommentsPanel.updateComments(CommentsPanel.java:180)
>                                               [       ]   at org.micromanager.display.internal.inspector.CommentsPanel.access$000(CommentsPanel.java:46)
>                                               [       ]   at org.micromanager.display.internal.inspector.CommentsPanel$1.run(CommentsPanel.java:67)
>                                               [       ]   at java.lang.Thread.run(Thread.java:745)
>                                               [       ] Thread 39 [TaggedImage sink thread] BLOCKED
>                                               [       ]   at org.micromanager.display.internal.CanvasUpdateQueue.enqueue(CanvasUpdateQueue.java:145)
>                                               [       ]   at org.micromanager.display.internal.DefaultDisplayWindow.setDisplayedImageTo(DefaultDisplayWindow.java:698)
>                                               [       ]   at org.micromanager.display.internal.ScrollerPanel.onNewImage(ScrollerPanel.java:464)
>                                               [       ]   at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)
>                                               [       ]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>                                               [       ]   at java.lang.reflect.Method.invoke(Method.java:606)
>                                               [       ]   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>                                               [       ]   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>                                               [       ]   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>                                               [       ]   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>                                               [       ]   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>                                               [       ]   at org.micromanager.internal.utils.PrioritizedEventBus.post(PrioritizedEventBus.java:63)
>                                               [       ]   at org.micromanager.data.internal.DefaultDatastore.putImage(DefaultDatastore.java:202)
>                                               [       ]   at org.micromanager.data.internal.pipeline.DefaultPipeline.insertImage(DefaultPipeline.java:111)
>                                               [       ]   at org.micromanager.acquisition.internal.DefaultTaggedImageSink$1.run(DefaultTaggedImageSink.java:70)
>                                               [       ] Thread 40 [Scrollbar panel update thread] TIMED_WAITING
>                                               [       ]   at java.lang.Thread.sleep(Native Method)
>                                               [       ]   at org.micromanager.display.internal.ScrollerPanel.runUpdateThread(ScrollerPanel.java:413)
>                                               [       ]   at org.micromanager.display.internal.ScrollerPanel.access$100(ScrollerPanel.java:68)
>                                               [       ]   at org.micromanager.display.internal.ScrollerPanel$1.run(ScrollerPanel.java:192)
>                                               [       ]   at java.lang.Thread.run(Thread.java:745)
>                                               [       ] Thread 42 [zSelector] WAITING
>                                               [       ]   at java.lang.Object.wait(Native Method)
>                                               [       ]   at java.lang.Object.wait(Object.java:503)
>                                               [       ]   at ij.gui.StackWindow.run(StackWindow.java:228)
>                                               [       ]   at java.lang.Thread.run(Thread.java:745)
>                                               [       ] Thread 44 [FPS display blank] WAITING
>                                               [       ]   at java.lang.Object.wait(Native Method)
>                                               [       ]   at java.lang.Object.wait(Object.java:503)
>                                               [       ]   at java.util.TimerThread.mainLoop(Timer.java:526)
>                                               [       ]   at java.util.TimerThread.run(Timer.java:505)

**Comment by nicost** [comment]
You can apply pull request #459.  Removing that lock should avoid the deadlock that you (and I and likely many others) ran into.  I have not yet discovered downsides, but the threads and locks in the display code needs careful study.

**Comment by nicost** [comment]
I think this has been fixed now.  Please do open a new ticket whenever you experience a MDA hang with the current code
