### ISSUE TITLE
Closing a datastore does not always close filehandle

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#470]
Run an acquisition in memory (i.e. not saving automatically).  Save (using the disk icon).  Close the display.  Try deleting the data on disk and discover this to be impossible since mm did not close the file handle.  The same issue is encountered when acquiring to a RAM datastore in a script and then saving to file using the store.save() method.

**Comment by hadim** [comment]
I confirm the issue.

**Comment by nicost** [comment]
Fixed in PR #471

**Comment by nicost** [comment]
I still occasionally see an issue with Metadata.txt not closing.  Will investigate.

**Comment by nicost** [comment]
I have not encountered this issue recently.
