### ISSUE TITLE
Deadlock while starting an acquisition

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#480]
I have a potential fix, needs testing:

debug:
2016-11-03T17:23:11.738566 tid5020 [IFO,LogManager] Enabled logging to stderr
Asked to load file at path C:\Program Files\Micro-Manager-2.0beta\GlobalUserProfile.txt which doesn't exist; instead providing a default empty PropertyMap.
2016-11-03T17:23:11.832167 tid5020 [IFO,LogManager] Enabled primary log file C:\Program Files\Micro-Manager-2.0beta\CoreLogs\CoreLog20161103T172311_pid4248.txt
2016-11-03T17:23:11.832167 tid5020 [IFO,App] User: Vale Lab
2016-11-03T17:23:11.832167 tid5020 [IFO,App] Host: Uberscope
2016-11-03T17:23:11.832167 tid5020 [IFO,App] MM Studio version: 2.0.x dev
---- snip ---
2016-11-03T17:24:25.703410 tid2396 [IFO,App] EDTHangLogger: Missed heartbeat; waiting to see if we are stuck on a single event
2016-11-03T17:24:26.704467 tid2396 [IFO,App] EDTHangLogger: Event handling has exceeded at least 1000 ms (currently 5500 ms since heartbeat timebase)
                                   [       ] Stack traces follow (note: thread states queried later than stack traces)
                                   [       ] Thread 2 [Reference Handler] WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at java.lang.Object.wait(Object.java:485)
                                   [       ]   at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:116)
                                   [       ] Thread 3 [Finalizer] WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:118)
                                   [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:134)
                                   [       ]   at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:171)
                                   [       ] Thread 4 [Signal Dispatcher] RUNNABLE
                                   [       ] Thread 5 [Attach Listener] RUNNABLE
                                   [       ] Thread 13 [Java2D Disposer] WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:118)
                                   [       ]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:134)
                                   [       ]   at sun.java2d.Disposer.run(Disposer.java:127)
                                   [       ]   at java.lang.Thread.run(Thread.java:662)
                                   [       ] Thread 14 [AWT-Shutdown] WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at java.lang.Object.wait(Object.java:485)
                                   [       ]   at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:265)
                                   [       ]   at java.lang.Thread.run(Thread.java:662)
                                   [       ] Thread 15 [AWT-Windows] RUNNABLE
                                   [       ]   at sun.awt.windows.WToolkit.eventLoop(Native Method)
                                   [       ]   at sun.awt.windows.WToolkit.run(WToolkit.java:293)
                                   [       ]   at java.lang.Thread.run(Thread.java:662)
                                   [       ] Thread 18 [AWT-EventQueue-0] BLOCKED
                                   [       ]   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
                                   [       ]   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
                                   [       ]   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
                                   [       ]   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
                                   [       ]   at org.micromanager.display.internal.DefaultDisplayWindow.setDisplaySettings(DefaultDisplayWindow.java:791)
                                   [       ]   at org.micromanager.display.internal.DefaultDisplayWindow.setDisplaySettings(DefaultDisplayWindow.java:773)
                                   [       ]   at org.micromanager.display.internal.LUTMaster.updateDisplayLUTForChannel(LUTMaster.java:319)
                                   [       ]   at org.micromanager.display.internal.LUTMaster.updateDisplayLUTs(LUTMaster.java:289)
                                   [       ]   at org.micromanager.display.internal.LUTMaster.initializeDisplay(LUTMaster.java:261)
                                   [       ]   at org.micromanager.display.internal.CanvasUpdateQueue.showImage(CanvasUpdateQueue.java:333)
                                   [       ]   at org.micromanager.display.internal.CanvasUpdateQueue.consumeImages(CanvasUpdateQueue.java:219)
                                   [       ]   at org.micromanager.display.internal.CanvasUpdateQueue.access$000(CanvasUpdateQueue.java:71)
                                   [       ]   at org.micromanager.display.internal.CanvasUpdateQueue$1.run(CanvasUpdateQueue.java:158)
                                   [       ]   at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
                                   [       ]   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:672)
                                   [       ]   at java.awt.EventQueue.access$400(EventQueue.java:81)
                                   [       ]   at java.awt.EventQueue$2.run(EventQueue.java:633)
                                   [       ]   at java.awt.EventQueue$2.run(EventQueue.java:631)
                                   [       ]   at java.security.AccessController.doPrivileged(Native Method)
                                   [       ]   at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
                                   [       ]   at java.awt.EventQueue.dispatchEvent(EventQueue.java:642)
                                   [       ]   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
                                   [       ]   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
                                   [       ]   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
                                   [       ]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
                                   [       ]   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
                                   [       ]   at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
                                   [       ] Thread 21 [org.netbeans.modules.debugger.jpda.visual AWT Access Loop] TIMED_WAITING
                                   [       ]   at java.lang.Thread.sleep(Native Method)
                                   [       ]   at org.netbeans.modules.debugger.jpda.visual.remote.RemoteAWTService$AWTAccessLoop.run(RemoteAWTService.java:236)
                                   [       ]   at java.lang.Thread.run(Thread.java:662)
                                   [       ] Thread 22 [DestroyJavaVM] RUNNABLE
                                   [       ] Thread 23 [User profile save thread] TIMED_WAITING
                                   [       ]   at java.lang.Thread.sleep(Native Method)
                                   [       ]   at org.micromanager.internal.utils.DefaultUserProfile.runSaveThread(DefaultUserProfile.java:191)
                                   [       ]   at org.micromanager.internal.utils.DefaultUserProfile.access$000(DefaultUserProfile.java:22)
                                   [       ]   at org.micromanager.internal.utils.DefaultUserProfile$1.run(DefaultUserProfile.java:168)
                                   [       ] Thread 24 [EDTHangLogger timer] RUNNABLE
                                   [       ]   at java.lang.Thread.dumpThreads(Native Method)
                                   [       ]   at java.lang.Thread.getAllStackTraces(Thread.java:1530)
                                   [       ]   at org.micromanager.internal.diagnostics.EDTHangLogger.checkForHang(EDTHangLogger.java:233)
                                   [       ]   at org.micromanager.internal.diagnostics.EDTHangLogger.access$200(EDTHangLogger.java:34)
                                   [       ]   at org.micromanager.internal.diagnostics.EDTHangLogger$4.run(EDTHangLogger.java:220)
                                   [       ]   at java.util.TimerThread.mainLoop(Timer.java:512)
                                   [       ]   at java.util.TimerThread.run(Timer.java:462)
                                   [       ] Thread 27 [TimerQueue] TIMED_WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at javax.swing.TimerQueue.run(TimerQueue.java:232)
                                   [       ]   at java.lang.Thread.run(Thread.java:662)
                                   [       ] Thread 28 [D3D Screen Updater] TIMED_WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at sun.java2d.d3d.D3DScreenUpdateManager.run(D3DScreenUpdateManager.java:419)
                                   [       ]   at java.lang.Thread.run(Thread.java:662)
                                   [       ] Thread 48 [Thread-23] TIMED_WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at bsh.util.JConsole$BlockingPipedInputStream.read(JConsole.java:771)
                                   [       ]   at java.io.PipedInputStream.read(PipedInputStream.java:361)
                                   [       ]   at java.io.InputStream.read(InputStream.java:82)
                                   [       ]   at bsh.util.JConsole.inPipeWatcher(JConsole.java:667)
                                   [       ]   at bsh.util.JConsole.run(JConsole.java:677)
                                   [       ]   at java.lang.Thread.run(Thread.java:662)
                                   [       ] Thread 49 [BeanShell interpreter] TIMED_WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at java.io.PipedInputStream.read(PipedInputStream.java:310)
                                   [       ]   at java.io.PipedInputStream.read(PipedInputStream.java:361)
                                   [       ]   at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:264)
                                   [       ]   at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:306)
                                   [       ]   at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:158)
                                   [       ]   at java.io.InputStreamReader.read(InputStreamReader.java:167)
                                   [       ]   at bsh.JavaCharStream.FillBuff(JavaCharStream.java:160)
                                   [       ]   at bsh.JavaCharStream.ReadByte(JavaCharStream.java:188)
                                   [       ]   at bsh.JavaCharStream.readChar(JavaCharStream.java:289)
                                   [       ]   at bsh.JavaCharStream.BeginToken(JavaCharStream.java:209)
                                   [       ]   at bsh.ParserTokenManager.getNextToken(ParserTokenManager.java:2072)
                                   [       ]   at bsh.Parser.jj_ntk(Parser.java:6022)
                                   [       ]   at bsh.Parser.Line(Parser.java:163)
                                   [       ]   at bsh.Interpreter.Line(Interpreter.java:1011)
                                   [       ]   at bsh.Interpreter.run(Interpreter.java:462)
                                   [       ]   at java.lang.Thread.run(Thread.java:662)
                                   [       ] Thread 62 [Thread-33] TIMED_WAITING
                                   [       ]   at java.lang.Thread.sleep(Native Method)
                                   [       ]   at org.micromanager.display.internal.inspector.MetadataPanel.updateMetadata(MetadataPanel.java:262)
                                   [       ]   at org.micromanager.display.internal.inspector.MetadataPanel.access$000(MetadataPanel.java:62)
                                   [       ]   at org.micromanager.display.internal.inspector.MetadataPanel$1.run(MetadataPanel.java:107)
                                   [       ]   at java.lang.Thread.run(Thread.java:662)
                                   [       ] Thread 63 [Thread-34] TIMED_WAITING
                                   [       ]   at java.lang.Thread.sleep(Native Method)
                                   [       ]   at org.micromanager.display.internal.inspector.CommentsPanel.updateComments(CommentsPanel.java:180)
                                   [       ]   at org.micromanager.display.internal.inspector.CommentsPanel.access$000(CommentsPanel.java:46)
                                   [       ]   at org.micromanager.display.internal.inspector.CommentsPanel$1.run(CommentsPanel.java:67)
                                   [       ]   at java.lang.Thread.run(Thread.java:662)
                                   [       ] Thread 74 [Scrollbar panel update thread] TIMED_WAITING
                                   [       ]   at java.lang.Thread.sleep(Native Method)
                                   [       ]   at org.micromanager.display.internal.ScrollerPanel.runUpdateThread(ScrollerPanel.java:422)
                                   [       ]   at org.micromanager.display.internal.ScrollerPanel.access$100(ScrollerPanel.java:68)
                                   [       ]   at org.micromanager.display.internal.ScrollerPanel$1.run(ScrollerPanel.java:192)
                                   [       ]   at java.lang.Thread.run(Thread.java:662)
                                   [       ] Thread 75 [zSelector] WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at java.lang.Object.wait(Object.java:485)
                                   [       ]   at ij.gui.StackWindow.run(StackWindow.java:226)
                                   [       ]   at java.lang.Thread.run(Thread.java:662)
                                   [       ] Thread 86 [FPS display blank] WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at java.lang.Object.wait(Object.java:485)
                                   [       ]   at java.util.TimerThread.mainLoop(Timer.java:483)
                                   [       ]   at java.util.TimerThread.run(Timer.java:462)
                                   [       ] Thread 99 [TaggedImage sink thread] BLOCKED
                                   [       ]   at org.micromanager.display.internal.CanvasUpdateQueue.enqueue(CanvasUpdateQueue.java:145)
                                   [       ]   at org.micromanager.display.internal.CanvasUpdateQueue.redraw(CanvasUpdateQueue.java:544)
                                   [       ]   at org.micromanager.display.internal.CanvasUpdateQueue.reapplyLUTs(CanvasUpdateQueue.java:535)
                                   [       ]   at org.micromanager.display.internal.CanvasUpdateQueue.onNewDisplaySettings(CanvasUpdateQueue.java:576)
                                   [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                   [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
                                   [       ]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
                                   [       ]   at java.lang.reflect.Method.invoke(Method.java:597)
                                   [       ]   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
                                   [       ]   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
                                   [       ]   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
                                   [       ]   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
                                   [       ]   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
                                   [       ]   at org.micromanager.display.internal.DefaultDisplayWindow.setDisplaySettings(DefaultDisplayWindow.java:791)
                                   [       ]   at org.micromanager.display.internal.DefaultDisplayWindow.setDisplaySettings(DefaultDisplayWindow.java:773)
                                   [       ]   at org.micromanager.display.internal.DefaultDisplayWindow.receiveNewImage(DefaultDisplayWindow.java:1094)
                                   [       ]   at org.micromanager.display.internal.DefaultDisplayWindow.onNewImage(DefaultDisplayWindow.java:1062)
                                   [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                   [       ]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
                                   [       ]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
                                   [       ]   at java.lang.reflect.Method.invoke(Method.java:597)
                                   [       ]   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
                                   [       ]   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
                                   [       ]   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
                                   [       ]   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
                                   [       ]   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
                                   [       ]   at org.micromanager.internal.utils.PrioritizedEventBus.post(PrioritizedEventBus.java:63)
                                   [       ]   at org.micromanager.data.internal.DefaultDatastore.putImage(DefaultDatastore.java:202)
                                   [       ]   at org.micromanager.data.internal.pipeline.DefaultPipeline.insertImage(DefaultPipeline.java:111)
                                   [       ]   at org.micromanager.acquisition.internal.DefaultTaggedImageSink$1.run(DefaultTaggedImageSink.java:70)
                                   [       ] Thread 103 [Scrollbar panel update thread] TIMED_WAITING
                                   [       ]   at java.lang.Thread.sleep(Native Method)
                                   [       ]   at org.micromanager.display.internal.ScrollerPanel.runUpdateThread(ScrollerPanel.java:422)
                                   [       ]   at org.micromanager.display.internal.ScrollerPanel.access$100(ScrollerPanel.java:68)
                                   [       ]   at org.micromanager.display.internal.ScrollerPanel$1.run(ScrollerPanel.java:192)
                                   [       ]   at java.lang.Thread.run(Thread.java:662)
                                   [       ] Thread 104 [zSelector] WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at java.lang.Object.wait(Object.java:485)
                                   [       ]   at ij.gui.StackWindow.run(StackWindow.java:226)
                                   [       ]   at java.lang.Thread.run(Thread.java:662)
                                   [       ] Thread 106 [FPS display blank] WAITING
                                   [       ]   at java.lang.Object.wait(Native Method)
                                   [       ]   at java.lang.Object.wait(Object.java:485)
                                   [       ]   at java.util.TimerThread.mainLoop(Timer.java:483)
                                   [       ]   at java.util.TimerThread.run(Timer.java:462)

**Comment by kthorn** [comment]
I see what looks like the same hang in the latest nightly build. I was able to acquire a few images before it occurred, so it appears to be sporadic.

**Comment by nicost** [comment]
It is useful to look at the threads that are "BLOCKED" (hopefully recorded in the Corelog).  If the EDT (and a second thread) are blocked at the same place as in the trace above, then it is the smae deadlock (there may be others, and fixes to this deadlock may uncover yet other deadlocks).  B.t.w., this logging is very nice!

**Comment by nicost** [comment]
PR #482 hasa fix for this deadlock.  On this particular microscope system it now appears 100% of the time.  After applying the PR I have not seen it anymore (or any other deadlock, however, this is only with limited testing).

**Comment by nicost** [comment]
Merged #482
