### ISSUE TITLE
Rules for using Core notifications without deadlock are unclear

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#498]
In mm2, we might consider using a second, asynchronous event bus (AsyncEventBus) for these to avoid deadlock.

**Comment by nicost** [comment]
@marktsuchida Shall we have a look at this now?

**Comment by marktsuchida** [comment]
Yes. I think there are mainly two options: an async event bus, or `SwingUtilities.invokeLater()`, i.e., always run the callbacks on the EDT. For GUI updates the latter makes more sense, but if most callbacks need to do further background processing/querying before updating the GUI anyway, perhaps it is better to use an async event bus.

**Comment by nicost** [comment]
It looks like all callbacks in org.micromanager.events.internal.CoreEventCallback are on the EDT.

Close ticket?

**Comment by marktsuchida** [comment]
Actually it's probably best to update that class so that it uses `invokeLater` unconditionally, even when already on the EDT. Otherwise there could be cases where a callback on the EDT calls back into the Core, resulting in further callbacks, which seems dangerous.

**Comment by nicost** [comment]
Implemented in PR #754
