### ISSUE TITLE
Hardware Configuration Wizard does not retain focus direction settings

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#513]
Thanks to Henry Pinkard for reporting this.
> Hardware configuration wizard seems to erase the setting for focus direction of the Z drive (i.e. positive toward sample or away from sample). If you open Hardware configuration wizard but cancel and dont save, this setting gets arased from config file.

**Comment by nicost** [comment]
I am unable to reproduce this bug.  Created a configuration based on the demo config and set thez drive direction.  Went into the HCW, and cancelled at various steps (by pressing the x button in the window top).  Z-drive direction was always retained.
