### ISSUE TITLE
Alerts window is brought to the foreground when postAlert() is called

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#514]
This behavior makes it impossible to post notices to the user, since it annoyingly forces the user to bring back focus to the window they were working with.  If it is sometimes desirable to set focus to the alerts window, can a flag be added so that this behavior can be modified?

**Comment by marktsuchida** [comment]
Agreed. Will do.

**Comment by nicost** [comment]
This seems to work fine now
