### ISSUE TITLE
Alerts Window: Can only copy one line at a time

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#515]
When position multiple alerts to the Alerts window using the postAlert() function, only one line can be copied to the system clipboard.  That makes it very impractical to collect useful information in the Alerts window.  Maybe I am overloading the Alerts window with unintended functionality, but it is otherwise so much nicer than opening a random output text window.

**Comment by marktsuchida** [comment]
There is now a Copy All button.
