### ISSUE TITLE
mm2: Image viewer color incorrectly initialized?

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#52]
Start with fresh user profile and standard demo config.

MDA, 6 time points, Z stack of 0-5 at step = 1, channel group "Channel", create two channels. Run MDA.

The assigned channels colors are blue and orange, and the inspector says Color mode is Grayscale, but the actual image is rendered in colors that do not match either.

Tested on OS X.

**Comment by ChrisWeisiger** [comment]
Improved in 1e23ac259c2588cd4d7448bb8dffc5d9bf1df01f. Now the channel colors are only briefly wrong and are fixed as soon as we do an update of the display. Hopefully we will eventually get a proper fix so the display is never wrong.

**Comment by ChrisWeisiger** [comment]
It appears that commit 1ba5576f1279418d5297a008d2abca57ae8b87ef has fully fixed this.
