### ISSUE TITLE
Coords.CHANNEL not equivalent to Coords.CHANNEL_SHORT

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#548]
For a datastore with 2 channels:
datastore.getAxisLength(Coords.CHANNEL) != datastore.getAxisLength(Coords.CHANNEL_SHORT).

datastore.getAxisLength(Coords.CHANNEL) returns 2 (correct)
datastore.getAxisLength(Coords.CHANNEL_SHORT) returns 0 (incorrect).

Is this indeed a bug, or is there some intention that I do not understand?

**Comment by marktsuchida** [comment]
Not a bug, I don't think, but definitely a source of potential confusion. The `_SHORT` versions are for use with the `DefaultCoords.fromNormalizedString` method, but then I'm not sure why the `_SHORT` final fields need to be exposed in the API. We should probably remove it if we can confirm that that is the only way it is used.

**Comment by nicost** [comment]
Looks to me that those _SHORT versions should indeed not be exposed if they are not intended to be used by outside code.

**Comment by nicost** [comment]
Looks like those are no longer present
