### ISSUE TITLE
Calibration of snap/live window sometimes not correct

### ISSUE THREAD

**Issue by mutterer** [micro-manager/micro-manager#559]
with Micro-Manager-2.0.0-beta3-20170405.

I get two different behaviours depending on whether I first snap an image or change the objective.

1- start MM2 with demo config
change objective to 40x
snap an image
run the test macro => 0.25 0.25 1 µm (correct)

2- start MM2 with demo config
snap an image at default 10x
change objective to 40x
snap an image
run the test macro => 1 1 1 µm  (not correct)

 Test macro:
getVoxelSize(x,y,z,unit);
print(x,y,z,unit);

**Comment by nicost** [comment]
This appears to be fixed now (in 2.0-gamma).  If this issue still exists for you with the current or later nightly build, please re-open.
