### ISSUE TITLE
Groups and presents unavailable - error when trying to add them

### ISSUE THREAD

**Issue by npyoung** [micro-manager/micro-manager#561]
Adding a group with the + button results in the follow error dialog:

```Error: org.micromanager.internals.utils.PropertyTableData.update(PropertyTableData.java:235)```

The Group Editor window opens, but no device properties are listed. However, when opening the Device Property Browser, all configured properties show up as expected, and the microscope can be controlled. It's just groups and presets that don't work.

This occurs when making a new configuration from scratch, or when loading up a config made in MM 1.4. In the later case, the existing groups and presets do not appear under "Configuration settings" on the main window.

OS: Windows 7
MM: v2.0.0-beta2

**Comment by nicost** [comment]
Can you try the same in the latest nightly build?  Also good to test with the demo configuration (if the problem persists in the nightly build).

**Comment by npyoung** [comment]
This was the latest nightly build as of the date of posting - 4acd302 was the only change since then.

Problem persists using the demo config too.

**Comment by nicost** [comment]
I can not reproduce this problem.  Generate a Problem Report and look for Java exceptions.  Copy the whole Exception chain, hopefully it provides a clue.

**Comment by npyoung** [comment]
Since trying to reproduce this with the latest nightlies (5/25), the bug seems to have disappeared.
