### ISSUE TITLE
Export as displayed should not copy colored outline

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#564]
the export to ImageJ functionality is fantastic.  One annoyance: when using Color or Composite mode, there is a colored line around the image (presumably to indicate which channel is selected) that is also copied to ImageJ (and presumably written to file if that output mode was selected).  I can not imagine that line ever to be desirable in exported images, and it is a lot of work to remove, so it would be nicer to crop it out right away, or add an option to remove it in the display so that it does not get exported..

**Comment by marktsuchida** [comment]
Fixed, I believe.
