### ISSUE TITLE
[MM2] stage control via keyboard moves by microns rather than pixels

### ISSUE THREAD

**Issue by julou** [micro-manager/micro-manager#567]
The [Interactive Stage Movements](https://micro-manager.org/wiki/Micro-Manager_User%27s_Guide#Interactive_Stage_Movements) of MM1.4 are very handy.

Although [not documented in MM2](https://micro-manager.org/wiki/Version_2.0_Users_Guide#Stage_Control), they're implemented in MM2 (at least for xy). Unfortunately, the displacement follows the description of MM1.4 but in microns rather than pixels (i.e. a simple arrow key moves by 10 µm, and a shift-arrow by 2.048mm on our 2048x2048 Flash4!!!).
I would be great to see this fixed since we use it a lot in MM1.4. 

Also, it would be very convenient in my opinion that the modifier keys use the displacement settings specified in the [stage control window](https://micro-manager.org/wiki/Version_2.0_Users_Guide#Stage_Control), e.g. normal for 10pixels, ctrl for '>' distance, alt for '>>' distance and shift for '>>>' distance. Even better if those >, >>, and >>> distances could be set to 1 pixel, half the chip width and full chip width by default… one would get the convenience of MM1.4 shortcuts with an extra layer of flexibility (useful e.g. when using non-square ROIs).

**Comment by nicost** [comment]
Addressed in PR #741.  Also discussed in another Issue, so closing this one for now.
