### ISSUE TITLE
[mm2] duplicated org/json/*classe in MMJ_.jar and MMCoreJ.jar

### ISSUE THREAD

**Issue by BioinfoTongLI** [micro-manager/micro-manager#569]
Hello,
I'm writing a plugin using both MMJ_.jar and MMCoreJ.jar as dependencies. All the dependencies of this plugin were handled by maven, inherent the parent 
`	<parent>
		<groupId>sc.fiji</groupId>
		<artifactId>pom-fiji</artifactId>
		<version>26.1.1</version>
</parent>`
and i ignore the duplicated classes using this plugin
`<artifactId>maven-enforcer-plugin</artifactId>
			<configuration>
				<rules>
					<banClasses
					implementation="org.scijava.maven.plugin.enforcer.BanDuplicateClasses">
						<dependencies>
						
						<dependency>
						<artifactId>MMJ_</artifactId>
							<ignoreClasses>
							<ignoreClass>org/json/*</ignoreClass>
							</ignoreClasses>
						</dependency>
						</dependencies>
					<findAllDuplicates>true</findAllDuplicates>
					</banClasses>
				</rules>
</configuration>`

I just noticed that the sc.fiji thread seems to be obselete now.
So i moved to scijava as recommanded. 

`        <groupId>org.scijava</groupId>  
        <artifactId>pom-scijava</artifactId>  
        <version>14.0.0</version>`

However, the new plugin banDuplicateClasses is not working correctly (at least on my Mac sierra and Ubuntu 16.04, or maybe i didn't do it right).
So i began to wonder  why the org/json classes are duplicated in those two jars?

Are they there on purpose or it's a mistake?

It would be nice if there is only one version of json, so that scijava will be happy.
Thank you a lot!

**Comment by nicost** [comment]
Fixed in PR #728.  Sorry this took so long!
