### ISSUE TITLE
[mm2] MMStudio fails to build on Linux

### ISSUE THREAD

**Issue by Armavica** [micro-manager/micro-manager#573]
I am trying to compile mm2 on Linux, but MMStudio fails to build, the error seems to be that the file `org.scijava.plugin.Plugin` cannot be found. Do you have an idea why this happens? I attach what seems relevant, please let me know if you need more.

- [`./configure`](https://paste.fulltxt.net/-1VfePSMBJgLl)
- `make fetchdeps` reports success
- [`make`](https://paste.fulltxt.net/JO@_QnAJP)

**Comment by kmdouglass** [comment]
Did you download the 3rd party libraries from the `3rdpartypublic` SVN repository and place the folder in the same directory as the one containing the mm2 source code folder?

See [this section](https://github.com/micro-manager/micro-manager/blob/mm2/doc/how-to-build.md#obtaining-the-source-code) of the build directions.

**Comment by Armavica** [comment]
Yes, I did.

**Comment by cErikson** [comment]
I am also having this problem. I am building with the arch with the commit 88ab1ff051b548aafced024c46f902720eb9d553.

fetchdeps reports:
`[ivy:resolve] 	found org.scijava#scijava-common;2.46.0 in central`

**Comment by cErikson** [comment]
I managed to resolve this problem by changing the default compiler from OpenJDK10 to OpenJDK8

**Comment by dedeibel** [comment]
I can recommend this build script for linux: https://github.com/hadim/mm_scripts/blob/master/build-mm.sh
