### ISSUE TITLE
Documentation for device adapter Initialed/Shutdown inaccurate/incomplete

### ISSUE THREAD

**Issue by lukas-lang** [micro-manager/micro-manager#586]
Currently, the page on [Building Micro-Manager device adapters](https://micro-manager.org/wiki/Building_Micro-Manager_Device_Adapters) lists the following requirements for Initialize & Shutdown: 

* No communication with the device before Initialize/after Shutdown 
* Repeated calls to a method should not do anything once it has been successfully run 
* Initialize/Shutdown reverse each other's effects which may be done repeatedly 

This however fails to mention one requirement: 

* If Shutdown is called on a device that has never been initialized, nothing should happen 

This can become a problem when a device earlier in the hardware configuration fails to load, which causes *all* devices to be shut down *regardless* of their state. I think it would be helpful to explicitly mention this behavior somewhere in the list of requirements - in my case, it took me hours to diagnose a crash caused by this (admittedly, most implantations of Initialize/Shutdown which check some kind of `initialized` flag fulfill this automatically)

**Comment by nicost** [comment]
Text added.
