### ISSUE TITLE
doc() convenience function broken for gui object 

### ISSUE THREAD

**Issue by mutterer** [micro-manager/micro-manager#594]
This is a very minor issue noticed in current MM1.4.
the beanshel doc() convenience function logic is broken regarding the gui object.

gui.getClass().getName() returns "org.micromanager.MMStudio"

which the doc function uses to build the following url:
http://valelab.ucsf.edu/~MM/doc/mmstudio/org/micromanager/MMStudio.html

The correct url to point to would rather be:
https://valelab4.ucsf.edu/~MM/doc/mmstudio/org/micromanager/api/ScriptInterface.html
 
The logic used to build the url is there:
https://github.com/micro-manager/micro-manager/blob/master/mmstudio/src/org/micromanager/scriptpanel/scriptpanel_startup.bsh#L74

Thanks !

**Comment by marktsuchida** [comment]
For the analogous issue in 2.0, see #926.
