### ISSUE TITLE
TCP/IP based command-and-control server

### ISSUE THREAD

**Issue by adamltaylor** [micro-manager/micro-manager#597]
I would like it (!) if you implemented a TCP/IP server in MM to allow command-and-control of MM by third-party applications.  I know that it's scriptable via Java, Matlab, and C++, but this would allow someone using any language to interface with MM easily.  It would also allow for remote control of MM across a network, which could be useful in some situations.

**Comment by nicost** [comment]
Please see discussion on the mailing list, for instance: http://micro-manager.3463995.n2.nabble.com/mWeb-alpha-released-for-Manager-2-0-td7588702.html
