### ISSUE TITLE
Multicam: 2nd EM camera stuck in 14-bit mode

### ISSUE THREAD

**Issue by pntbttrvbs** [micro-manager/micro-manager#598]
When using multiple iXon EMCCDs with the Multicam plugin, the second camera only gives data in 14-bit depth.

**Comment by nicost** [comment]
You may need to play a bit with the order that you do things.  With our iXons, only the 1MHz AD rate gives 16 bit data.  If yours behaves the same, it is likely that the second camera is not set the correct AD ratem so you may want to double check what is going one there.  B.t.w., these types of questions are better addressed on the mailing list.
