### ISSUE TITLE
mm2: Plugins loaded from current directory

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#60]
Code suggests that they are searched for within 'mmplugin' relative to the _current_ directory. I'm not sure what is the best method to determine the location (need to investigate 1.4 as well), we need to discuss, but it certainly shouldn't be the current directory, even though that works by accident with the default launcher on Windows/Mac.
(Also should discuss whether it is better to just use the classpath, as done by ImageJ2.)

**Comment by ChrisWeisiger** [comment]
We've switched to the 1.4 mechanism for determining the path, as of c89d35e0307527ad4a97e81c68714ffc2d38bb37.
