### ISSUE TITLE
Incompatible device interface version (required = 65; found = 68)

### ISSUE THREAD

**Issue by maobaoqi** [micro-manager/micro-manager#603]
I compile DemoCamera project and put mmgr_dal_DemoCamera.dll into micro-manager-2.0beta root directory, the software can not load it correctly when it run.I check the log and find the above information.

**Comment by nicost** [comment]
Make sure that your source and binaries are compatible, i.e. have the same Device Interface version.  The easiest way to do so is to use current source, and the latest nightly build as binary.

**Comment by maobaoqi** [comment]
@nicost thanks:)
