### ISSUE TITLE
OpenCVgrabber can not work on micro-manager2.0gamma.

### ISSUE THREAD

**Issue by maobaoqi** [micro-manager/micro-manager#604]
I use a generic usb camera in my computer and try to get images by OpenCVgrabber, but it can not work in the latest version.The screenshot is showed below.
![snipaste_20180119_135411](https://user-images.githubusercontent.com/3353791/35136889-401721ac-fd21-11e7-984b-acc468fef693.png)

**Comment by nicost** [comment]
See: https://micro-manager.org/wiki/Micro-Manager%20Community.  Please only post source code related issues on github.
