### ISSUE TITLE
"make install" fails when installing libraries for the Python wrapper on Linux

### ISSUE THREAD

**Issue by kmdouglass** [micro-manager/micro-manager#621]
# Problem
`make install` fails to place the libraries into the directory set by the `--prefix` of the configure script on Linux if the directory does not already exist. The failure results in an error in make and a non-zero exit code.

# Expected behavior
Running the `make install` command after successfully compiling the code with the `make` command should successfully copy all the libraries into their installation directory.

# Work around
Making the directory manually with `mkdir -p PREFIX/lib/micro-manager` before running `make install` allows for a successful install.

# Additional information

### Standard output
[make_install.log](https://github.com/micro-manager/micro-manager/files/1845547/make_install.log)

### Standard error

```
/usr/bin/install: cannot create regular file '/home/alphapi/micro-manager/lib/micro-manager': No su
ch file or directory                                                                              
make[3]: *** [install-exec-hook] Error 1
make[2]: *** [install-exec-am] Error 2
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1
```

## Configure flags

```
PYTHON="${python_dir}/bin/python3" ./configure \
    --prefix="/home/${user_name}/micro-manager" \
    --with-python="/usr/include/python3.5" \
    --with-boost-libdir="/usr/lib/arm-linux-gnueabihf" \
    --with-boost="/usr/include/boost" \
    --disable-java-app \
    --disable-install-dependency-jars \
    --with-java="no"
```

## Versions

The mm2 branch, commit number commit 7f05d45f18

```
uname -a
Linux HOST_NAME 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 armv7l GNU/Li
nux 
```

## Notes

- This fix probably just requires a `mkdir` command in the install script.
- The commands were run as root; I will change the folder ownership later.
- I do not think that the problem is due to building MM on an ARM processor.

**Comment by marktsuchida** [comment]
Thanks for the detailed report. Fixed in 1.4; will be merged into mm2 shortly.
