### ISSUE TITLE
device detection (port scanning) broken with TCP/IP ports

### ISSUE THREAD

**Issue by jondaniels** [micro-manager/micro-manager#625]
With TCPIPPort device adapter loaded the previously-working port scanning fails.  Problem goes away if TCPIPPort DLL is deleted.

I think I have figured out the cause.  With the TCPIPPort device adapter installed there is a TCP/IP port that now appears including in the list of available ports during the HCW.  When that port is evaluated in the following loop an error is thrown because the TCP/IP port doesn't have a Baud rate property (among others) and the MMCore code assumes all ports will have such a property.

https://github.com/micro-manager/micro-manager/blob/c8fc57369edd795a4c500d9ed3642fa74d34b9a8/MMCore/MMCore.cpp#L7375

(then property value is fetched in L7386)

The fix would be to either not scan TCP/IP ports or somehow make the MMCore code robust against this sort of error.  Note that the error happens and autodetect fails even if the device has already successfully been found on another port.

I'm going to try to propose a fix in a PR but I don't have a build system set up to test MMCore changes.

**Comment by marktsuchida** [comment]
PR #626 from @jondaniels fixes this.
