### ISSUE TITLE
Error message in Script panel unreadable in dark theme

### ISSUE THREAD

**Issue by lukas-lang** [micro-manager/micro-manager#637]
Would it be possible to change the color of exceptions when using the "Night" display background? Currently, it's almost impossible to read:

![image](https://user-images.githubusercontent.com/33105866/42134369-d6498e14-7d3a-11e8-8fd4-eb872eb2eeda.png)

vs:<br>

![image](https://user-images.githubusercontent.com/33105866/42134378-ef24ee24-7d3a-11e8-9f6d-004bd24a2669.png)
<br>
And similarly, some messages are nearly unreadable when using the "Day" background:
![image](https://user-images.githubusercontent.com/33105866/42134398-6154d9a0-7d3b-11e8-98e0-5549470ee8c5.png)

**Comment by nicost** [comment]
Feb., 1, 2020: Colors look much more readable (on my Windows system).  I find the red on dark quite readable, but can imagine that it is worse on dim screens.
