### ISSUE TITLE
[MM2] Clang throwing -Wc++11-narrowing errors.

### ISSUE THREAD

**Issue by cErikson** [micro-manager/micro-manager#670]
Clang is throwing -Wc++11-narrowing errors when compiling the device adapters. My work around is to specify g++ as the compiler.
[ I've attached the relevant errors. ](https://github.com/micro-manager/micro-manager/files/2948000/mm2_narrowing_errors.txt)

$Clang -v
g version 7.0.1 (tags/RELEASE_701/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/8.2.1
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/8.2.1
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/8.2.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64

**Comment by marktsuchida** [comment]
Until we update our code for C++11 and later, you probably need to pass `-std=c++03` as a compiler flag when configuring (with either clang or gcc).
