### ISSUE TITLE
space in folder name causes failed save

### ISSUE THREAD

**Issue by samjlord** [micro-manager/micro-manager#675]
If you put a space at the end of the folder name in the MDA window save section, the hardware starts the acquisition but the images do not appear. The folder is created without the space at the end of the folder name and uM cannot find the folder to save the data.

**Comment by nicost** [comment]
Fixed in 2.0-gamma: https://github.com/nicost/micro-manager/commit/5b82d96aeb2746b398ec298638efe25e8c59d257
