### ISSUE TITLE
mm2: Image windows no longer display image size in pixels and memory, and bit-depth

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#68]
That was useful information.  Any chance to get that back?

**Comment by marktsuchida** [comment]
Image size in micrometers is also missing, I think.

If it doesn't nicely fit, adding all this info to the top of the inspector _might_ be one option (though I like having it in the image window if possible).

Also created slightly related issue #70.

**Comment by ChrisWeisiger** [comment]
Fixed in d2a6f3240abc505751ff83769ac0ddf095c12b6e.
