### ISSUE TITLE
keyboard shortcuts gone after restart

### ISSUE THREAD

**Issue by andybra** [micro-manager/micro-manager#693]
the current version MM2gamma does not seem to retain the keyboard shortcuts set up like this:
https://micro-manager.org/wiki/Version_2.0_Users_Guide#Keyboard_Shortcuts

Since it doesn't work on any machine I try I suppose this is a bug? As soon as the program is restarted, it will have forgotten the shortcuts. I don't see any way of 'saving' them but the description on the micro-manager wiki (linked above) states, that this should be automatic?

**Comment by nicost** [comment]
That was a bug.  Fixed in PR#697.  Should be in tonight's build.
