### ISSUE TITLE
Running clear() in the scriptPanel also deletes mm and mmc instances

### ISSUE THREAD

**Issue by tlnagy** [micro-manager/micro-manager#707]
It would be useful to be able to clear all variables and functions from the workspace and it appears that `clear()` already does this, but it also deletes the `mm` and `mmc` objects. Currently, I have to reboot micro-manager if I update a function.

The solution from https://github.com/micro-manager/micro-manager/issues/170 doesn't work as well as `clear()` if there is major breakage in the scriptPanel

**Comment by nicost** [comment]
You can always re-create mm and mmc using:

```
import org.micromanager.MMStudio;
import org.micromanager.Studio;
import org.micromanager.internal.MMStudio;
mm = (Studio) MMStudio.getInstance();
mmc=mm.getCore();
```

Or use the Beanshell "unset()" command to specifically clear the variables you no longer want.
