### ISSUE TITLE
HCS plugin: Clicking on a well does not select it

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#71]
This makes it hard to add to a selection as the only way to select wlles is by dragging.  I am pretty sure that in 1.4 one can select a well by clicking.

**Comment by ChrisWeisiger** [comment]
The only selection bug I can find is that if you make a 1-dimensional drag selection, then you won't select anything. But if the mouse is stationary while you click, or if you drag in both X and Y, then the well(s) get properly selected. Certainly 1D drags ought to work as well, though. I've fixed the 1D drag issue in 9edde79b5d82bba90c8b1267cc54ee8592769d7b. Please let me know if you're still experiencing problems selecting wells.
