### ISSUE TITLE
MultiPageTiffStorage needs data in specific order

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#716]
The 2.0 API allows for data to be added to a Datastore in arbitrary order.  However, when choosing MultiPageTiffStorage as the Datastore, certain orders of addition of images lead to corrupt datasets.  The Beanshell script below illustrates this problem.  No exception is thrown by executing this code.  However, an Exception is caught many times on line 267 of org.micromanager.data.internal.multipagetiff.OMEMetadata.

Even though the example in this script is extreme, it quite often happens that data are missing, which may lead to data stored on disk without warning the user that reading the data back may be problematic.

```
import org.micromanager.data.Coordinates;

int positions = 7;
int slices = 6;
int tPoints = 4;
int channels = 3;

cb = Coordinates.builder();

cb.c(1).t(1).p(1).z(1);

store = mm.data().createMultipageTIFFDatastore(
      "C:\\tmp\\delme", true, false);

for (int p = positions; p > 0; p--) {
	for (int z = slices; z > 0; z--) {
		for (int t = tPoints; t > 0; t--) {
			for (int c = channels; c > 0; c--)  {
/*  this order works correctly
for (int p = 0; p < positions; p++) {
	for (int z = 0; z < slices; z++) {
		for (int t = 0; t < tPoints; t++) {
			for (int c = 0; c < channels; c++) {
*/
				cb.c(c).t(t).p(p).z(z);
				imgs = mm.live().snap(false);
				store.putImage(imgs.get(0).copyAtCoords(cb.build()));
			}
		}
	}
}

store.freeze();
mm.scripter().message("Done");
```

**Comment by marktsuchida** [comment]
Agreed. The TIFF datastores should throw an exception when images are added in an unsupported order.
