### ISSUE TITLE
mm2: Error while loading configuration containing Sutter Lambda Wheel

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#74]
While loading a configuration file (created in 1.4, loads fine in 1.4), MM shows the error message: Cannot set property "Timeout(ms)" to "500" [ Error in device "XL-Wheel": Invalid property name encountered: Timeout(ms) (2) ].  Then, the main window shows up without the Help menu (i.e., the user is unable to generate a Problem report).

**Comment by ChrisWeisiger** [comment]
The device adapters, core, etc. haven't been merged since June 10th; presumably this property was added since that time. We'll need to do another merge from 1.4 to fix this.

**Comment by ChrisWeisiger** [comment]
Thanks to Mark for merging in the changes from 1.4!
