### ISSUE TITLE
Evaluate need for method to discover that a new DataViewer was opened

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#763]
The NewDisplayWindowEvent seemed to do that job, but was not implemented.  Maybe this even is not needed for plugin writers, but it seems a useful hook into a running MM application.

**Comment by marktsuchida** [comment]
I'd say probably best if we can do without it. It's better if plugins attach (in various senses) to viewers through cleaner mechanisms, such as inspector panels, overlays, gear menu commands, etc.
