### ISSUE TITLE
vcs2019

### ISSUE THREAD

**Issue by triccyx** [micro-manager/micro-manager#774]
Moving from:
https://github.com/nicost/micro-manager/issues/98

I have two difficulties in opening a pull request about this:
- Can I use vcs2019 project inside a vcs2010 solution? I have only worked on MMCore and MMDevices.
- As I have worked with CMake my project are auto-generated and so should be checked by someone that is more expert than me (I'm from Linux world).  

Note:
I don't love cmake but I must admit that it is the "de facto" standard for cross-platform projects and it is very powerful. With a small about of lines, you can obtain the goal.
@mperrando @puccet

**Comment by nicost** [comment]
Yes, in that case probably less useful.  The main challenge in moving to a newer VS is the build process/machine itself, not so much configuration/build files.  Uprooting the ant/VS based build on Windows and plain old autoconf/automake on Unix is not worth it unless there is substantial gain.
