### ISSUE TITLE
MDA dialog does not properly update

### ISSUE THREAD

**Issue by nanthony21** [micro-manager/micro-manager#793]
This is true when setting acquisition settings through Studio.acquisitions().setAcquisitionSettings() as well as when settings are loaded from file in the GUI. The MDA dialog does not get property updated to reflect the actual settings even though the proper settings do appear to be loaded to the acquisition engine. 

I may have missed a few things but the following components do not update to represent the loaded settings: the "Channels" checkbox, the "Save Images" checkbox, and the "Name Prefix" textfield.

This appears to be a problem with AcqControlDlg.updateGuiContents()

**Comment by nicost** [comment]
Should work correctly after PR #882.  Please re-open if this is not true.
