### ISSUE TITLE
Pixel Size Calibration silently accepts presets with identical property values

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#818]
Simplest way to reproduce this using the demo configuration:
- Remove All Pixel Size configurations
- Add a config with only the DObjective label, set it to 10x.
- Create a new config, change the name but leave the DObjective set to 10x. Micro-Manager accepts this setting, but will display 0 nm/px in the main display.  Only one of these two identical configs will be matched.  

It surprises me that the Core allows this setting, and consider that the main bug.

**Comment by marktsuchida** [comment]
Fixed, thanks @zhangxiaosa!

**Comment by nicost** [comment]
Great that this is fixed in the UI, however, the Core should never allow for this, so this should be fixed there as well.

**Comment by marktsuchida** [comment]
Let's make that a separate issue (I'll create it), because the normal config groups have the same problem, not just the pixel size ones.

**Comment by nicost** [comment]
Wow, did not realize that.  Thanks!

**Comment by marktsuchida** [comment]
@nicost Yeah, I was a little surprised, too, but it is also complicated by how `CMMCore::defineConfig()` works, because each property value is set as a separate function call.
