### ISSUE TITLE
set preferred save mode in SequenceSettings

### ISSUE THREAD

**Issue by impact27** [micro-manager/micro-manager#834]
When running an acquisition with the acquisition manager, there is an option to use `org.micromanager.acquisition.SequenceSettings` with `runAcquisitionWithSettings`. However, there is no settings to say if the file should be saved as a multipage tiff ot as multiple files. This is one of the only settings from the acquisition pane that is not accessible. To change it, one must access some internal class:
```java
import org.micromanager.data.Datastore;
import org.micromanager.data.internal.DefaultDatastore;
DefaultDatastore.setPreferredSaveMode(mmStudio_,
    Datastore.SaveMode.SINGLEPLANE_TIFF_SERIES);
```
It would be nice to have that as an acquisition setting.

**Comment by nicost** [comment]
SequenceSettings now lets you specify the desired save mode.  Added in PR #882. Please re-open if it does not work, or needs further additions.
