### ISSUE TITLE
mm2: Image mouse-over status should be hidden when cursor not over image

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#86]
The x/y/value text in image viewer windows, and the yellow intensity indicator in the histograms, should be hidden when the mouse is not over the image (instead of the current behavior, which is to keep showing the position and intensity where the cursor was last over the image).

If it is hard to get a mouse-left-canvas event, one idea would be to set a timer (1-3 sec) after each mouse-moved-on-canvas event (cancel previous timer before setting new one). Then, when the timer fires, check if mouse is still on canvas and if not issue a mouse-has-left-canvas event. If mouse is still on canvas, restart the timer.

**Comment by ChrisWeisiger** [comment]
This was implemented in fd21b20f420350ca6bb2c4bb6f5c36cf83ffdfcc.
