### ISSUE TITLE
error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject

### ISSUE THREAD

**Issue by Richama2** [micro-manager/micro-manager#866]
I am having issues building MMstudio in netbeans. 
On more recent nightly builds I see this: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject

And older builds ~20200225: MMStudio fails to open from the imageJ menu. I believe it is there but I cannot see it as trying to open again calls an error.

Windows 10 64x. The source built using VS2015 compiles fine.

This is from the current nightly build and a fresh checkout on Netbeans 10 using JDK 1.8.

#------------------------------------------------------------------------------------------------------------------------------------------
ant -f C:\\Users\\Morga\\Documents\\NetBeansProjects\\JavaProject4 -Dnb.internal.action.name=build jar
init:
deps-jar:
Created dir: C:\Users\Morga\Documents\NetBeansProjects\JavaProject4\build
Updating property file: C:\Users\Morga\Documents\NetBeansProjects\JavaProject4\build\built-jar.properties
Created dir: C:\Users\Morga\Documents\NetBeansProjects\JavaProject4\build\classes
Created dir: C:\Users\Morga\Documents\NetBeansProjects\JavaProject4\build\empty
Created dir: C:\Users\Morga\Documents\NetBeansProjects\JavaProject4\build\generated-sources\ap-source-output
Compiling 472 source files to C:\Users\Morga\Documents\NetBeansProjects\JavaProject4\build\classes
warning: Supported source version 'RELEASE_6' from annotation processor 'com.jogamp.gluegen.structgen.CStructAnnotationProcessor' less than -source '1.8'
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\internal\SnapLiveManager.java:321: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
            JSONObject tags = tagged.tags;
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\internal\StaticInfo.java:167: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
         MDUtils.setXPositionUm(ti.tags, x_);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\internal\StaticInfo.java:168: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
         MDUtils.setYPositionUm(ti.tags, y_);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\internal\StaticInfo.java:171: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
         MDUtils.setZPositionUm(ti.tags, zPos_);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\DefaultImage.java:110: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
      JSONObject tags = tagged.tags;
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\DefaultImage.java:447: error: incompatible types: org.json.JSONObject cannot be converted to mmcorej.org.json.JSONObject
      return new TaggedImage(getRawPixels(), tags);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\FileSet.java:155: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
               img.tags, currentTiffFilename_));
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\FileSet.java:170: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
            checkForExpectedImageOrder(img.tags);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\FileSet.java:179: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
         int frame = MDUtils.getFrameIndex(img.tags);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\FileSet.java:182: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
            position = MDUtils.getPositionIndex(img.tags);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\FileSet.java:193: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
         omeMetadata_.addImageTagsToOME(img.tags, ifdCount_, baseFilename_, currentTiffFilename_, currentTiffUUID_);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\FileSet.java:199: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
         int frame = MDUtils.getFrameIndex(img.tags);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\FileSet.java:205: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
         int pos = MDUtils.getPositionIndex(img.tags);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\FileSet.java:214: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
            writeToMetadataFile(img.tags);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\MultipageTiffWriter.java:506: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
      addToIndexMap(DefaultCoords.legacyFromJSON(img.tags), offset);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\StorageMultipageTiff.java:376: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
               new FileSet(taggedImage.tags, this, omeMetadata_,
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\StorageMultipageTiff.java:383: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
         DefaultCoords coords = DefaultCoords.legacyFromJSON(taggedImage.tags);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\StorageMultipageTiff.java:392: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
         frame = MDUtils.getFrameIndex(taggedImage.tags);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\MultipageTiffReader.java:261: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
         augmentWithSummaryMetadata(tagged.tags);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\MultipageTiffReader.java:267: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
         Metadata metadata = DefaultMetadata.legacyFromJSON(tagged.tags);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\MultipageTiffReader.java:287: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
                  MDUtils.extractUserData(tagged.tags, blockedKeys)).build();
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\MultipageTiffReader.java:531: error: incompatible types: org.json.JSONObject cannot be converted to mmcorej.org.json.JSONObject
            return new TaggedImage(pixels, md);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\MultipageTiffReader.java:543: error: incompatible types: org.json.JSONObject cannot be converted to mmcorej.org.json.JSONObject
            return new TaggedImage(pixels, md);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\MultipageTiffReader.java:547: error: incompatible types: org.json.JSONObject cannot be converted to mmcorej.org.json.JSONObject
            return new TaggedImage(pixelBuffer.array(), md);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\MultipageTiffReader.java:553: error: incompatible types: org.json.JSONObject cannot be converted to mmcorej.org.json.JSONObject
            return new TaggedImage(pix, md);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\data\internal\multipagetiff\MultipageTiffReader.java:651: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
            coordsToOffset_.put(DefaultCoords.legacyFromJSON(ti.tags),
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\internal\utils\ImageUtils.java:100: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
      final JSONObject tags = taggedImage.tags;
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\internal\utils\ImageUtils.java:128: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
                ColorProcessor colorProcessor = new ColorProcessor(MDUtils.getWidth(taggedImage.tags), MDUtils.getHeight(taggedImage.tags), convertRGB32BytesToInt((byte []) taggedImage.pix));
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\internal\utils\ImageUtils.java:128: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
                ColorProcessor colorProcessor = new ColorProcessor(MDUtils.getWidth(taggedImage.tags), MDUtils.getHeight(taggedImage.tags), convertRGB32BytesToInt((byte []) taggedImage.pix));
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\internal\utils\ImageUtils.java:619: error: incompatible types: org.json.JSONObject cannot be converted to mmcorej.org.json.JSONObject
      return new TaggedImage(proc.getPixels(), tags);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\internal\utils\ImageUtils.java:638: error: incompatible types: org.json.JSONObject cannot be converted to mmcorej.org.json.JSONObject
      return new TaggedImage(pixels, tags);
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\internal\utils\ImageUtils.java:646: error: incompatible types: mmcorej.org.json.JSONArray cannot be converted to org.json.JSONArray
      JSONArray names = image.tags.names();
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\internal\utils\ImageUtils.java:652: error: incompatible types: mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject
         return new TaggedImage(image.pix, new JSONObject(image.tags, keys));
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\internal\utils\MDUtils.java:428: error: no suitable method found for isGRAY8(mmcorej.org.json.JSONObject)
      return isGRAY8(img.tags);
    method MDUtils.isGRAY8(org.json.JSONObject) is not applicable
      (argument mismatch; mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject)
    method MDUtils.isGRAY8(TaggedImage) is not applicable
      (argument mismatch; mmcorej.org.json.JSONObject cannot be converted to TaggedImage)
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\internal\utils\MDUtils.java:432: error: no suitable method found for isGRAY16(mmcorej.org.json.JSONObject)
      return isGRAY16(img.tags);
    method MDUtils.isGRAY16(org.json.JSONObject) is not applicable
      (argument mismatch; mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject)
    method MDUtils.isGRAY16(TaggedImage) is not applicable
      (argument mismatch; mmcorej.org.json.JSONObject cannot be converted to TaggedImage)
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\internal\utils\MDUtils.java:436: error: no suitable method found for isRGB32(mmcorej.org.json.JSONObject)
      return isRGB32(img.tags);
    method MDUtils.isRGB32(org.json.JSONObject) is not applicable
      (argument mismatch; mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject)
    method MDUtils.isRGB32(TaggedImage) is not applicable
      (argument mismatch; mmcorej.org.json.JSONObject cannot be converted to TaggedImage)
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\internal\utils\MDUtils.java:440: error: no suitable method found for isRGB64(mmcorej.org.json.JSONObject)
      return isRGB64(img.tags);
    method MDUtils.isRGB64(org.json.JSONObject) is not applicable
      (argument mismatch; mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject)
    method MDUtils.isRGB64(TaggedImage) is not applicable
      (argument mismatch; mmcorej.org.json.JSONObject cannot be converted to TaggedImage)
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\internal\utils\MDUtils.java:452: error: no suitable method found for isGRAY(mmcorej.org.json.JSONObject)
      return isGRAY(img.tags);
    method MDUtils.isGRAY(org.json.JSONObject) is not applicable
      (argument mismatch; mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject)
    method MDUtils.isGRAY(TaggedImage) is not applicable
      (argument mismatch; mmcorej.org.json.JSONObject cannot be converted to TaggedImage)
C:\Users\Morga\micro-manager\projects\micromanager\mmstudio\src\main\java\org\micromanager\internal\utils\MDUtils.java:456: error: no suitable method found for isRGB(mmcorej.org.json.JSONObject)
      return isRGB(img.tags);
    method MDUtils.isRGB(org.json.JSONObject) is not applicable
      (argument mismatch; mmcorej.org.json.JSONObject cannot be converted to org.json.JSONObject)
    method MDUtils.isRGB(TaggedImage) is not applicable
      (argument mismatch; mmcorej.org.json.JSONObject cannot be converted to TaggedImage)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
39 errors
1 warning
BUILD FAILED (total time: 4 seconds)

#------------------------------------------------------------------------------------------------------------------------------------------

**Comment by nicost** [comment]
It looks like you are mixing and matching different versions of source code and jars.  I don't know how you set up Netbeans, but it is always best to run 
`ant -f buildscripts/fetchdeps.xml`
from the micro-manager source directory.  Then include all jars in dependencies/artifacts/compile (and imagej).  That still does not give you MMCoreJ.jar and MMAcqEngine.jar.  If you do not build those yourself (which is the best approach to guarantee compatibility), then get them from a fresh nightly build.  Also please realize that these two are different for 1.4 and 2.0.

**Comment by Richama2** [comment]
Thanks!
