### ISSUE TITLE
Consider changing blacklist to blocklist

### ISSUE THREAD

**Issue by ctrueden** [micro-manager/micro-manager#868]
See https://twitter.com/leahculver/status/1269109776983547904

**Comment by nicost** [comment]
Thanks for the poke @ctrueden ! I found one in the SerialManager device adapater and one in an obscure buildscript.  Was there any specific instance you are aware of, or was this more in general?  I only searched the source, if you encountered this in any documentation, please let me know.

**Comment by ctrueden** [comment]
@nicost I found those instances in the source as well, but didn't check the docs. I did a mass grep over many repositories I track, and filed issues in places where I noticed them.

**Comment by nicost** [comment]
Thanks for doing that Curtis!  Closing now as this is fixed in svn, will sing through to the github sources soon.
