### ISSUE TITLE
mm2 display: bitdepth dropdown is no longer functional.

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#89]
Snap an image.  In the dropdown menu in the histogram section of the Image Inspector, select anything other than "Camera Depth".  Note that the histogram does not change.  Clicking the arrows on the left and right of the dropdown does have the expected effect.

**Comment by ChrisWeisiger** [comment]
This should be fixed in a26ce8425a4e8841dc06d92b802f5969b8fdbaeb.
