### ISSUE TITLE
File > Open (Virtual) does not bring up data inspection window

### ISSUE THREAD

**Issue by ieivanov** [micro-manager/micro-manager#914]
File > Open (Virtual) does not bring up the data inspection window. It'll be useful to be able to adjust the image histogram, create overlays, and display the metadata of virtual stacks.

**Comment by nicost** [comment]
It does for me.  Can you provide more context to reproduce the issue?  
I can imagine that something is going on with multiple threads running and the order in which certain calls/callbacks are mode but this will be hard to trouble shoot without a reproducible example.

**Comment by ieivanov** [comment]
Looks like this problem is fixed in the latest nightly build, I was having problems with an earlier version. Thanks Nico.
