### ISSUE TITLE
mm2: Minimum width of the Inspector Window is influenced by the length of the file name

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#93]
When opening /Volumes/nstuurman/Images/2014/20140915-BangaloreCourse/BPAECells2, the width of the inspector window increases so that it can fit the whole file name.  After opening that file, then snapping an image, the Inspector window gets even bigger, apparently to fit the long file name in the drop-down menu in the top of the window. The user can make the window less wide, however, the histograms scale to the large size of the window and not to the current size.

**Comment by ChrisWeisiger** [comment]
This is fixed now; the display name in the inspector window (and in its dropdown menu) is now truncated so that it won't distort the window size.
