### ISSUE TITLE
mm2: Intensity range limits obscured when close to histogram limits

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#95]
When dragging the upper (lower) triangular handle all the way to the left (right) edge of the histogram, the intensity value (displayed next to the handle) gets partially obscured.
The intensity value should be displayed to the right (left) of the handle when the handle is in the lower (upper) half of the available range.

**Comment by ChrisWeisiger** [comment]
This is now fixed for the top handle and greatly improved for the bottom handle.
