### ISSUE TITLE
Crash on quit after opening Hardware Configuration Wizard

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#957]
To reproduce (on Windows, 20200920 nightly):
- Start MM
- Open the Hardware Configuration Wizard
- Close the Hardware Configuration Wizard
- Quit MM

An `hs_err` log is generated.

Probably one of the device adapters is setting up something when it's loaded. After removing all device adapters (except for `DemoCamera`), the crash does not occur.

**Comment by zhangxiaosa** [comment]
It is mmgr_dal_Omicron.dll that caused the crash.

**Comment by nicost** [comment]
Great work Max! Let me know if I should contact Omicron or that we want to look into this ourselves.
