### ISSUE TITLE
Spinnaker fails to open shutter when starting Live

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager#969]
With Autoshutter enabled, starting Live does not open the shutter. Snaps and _finite_ sequence acquisitions are not affected.

See https://forum.image.sc/t/live-button-doesnt-trigger-auto-shutter/43428.

Probably a missing call to `PrepareForAcq()` in one of the two `StartSequenceAcquisition()` overloads.

**Comment by nicost** [comment]
Indeed. Fixed in PR #971
