### ISSUE TITLE
Quick Access Panels do not re-appear on application restart

### ISSUE THREAD

**Issue by nicost** [micro-manager/micro-manager#994]
Quick Access Panels are a nice feature making it possible for system configurators to create an easy work-flow for novice users.  However, after configuring a Quick Access Panel, it does not re-appear upon restarting MM.  That creates an unnecessary hurdle to use this feature.  We could, for instance, store which Quick Access Panels are open in the user profile and restore them on application restart.  This would greatly increase usability of Quick Access Panels.

**Comment by marktsuchida** [comment]
When configuring a Quick Access Panel, there is an option "Open on launch" with options "Never", "Always", and "Remember". It would probably make sense to make "Remember" the default.

**Comment by nicost** [comment]
Yes, please!

**Comment by nicost** [comment]
Done in PR #999
